<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Dự đoán Hỏng hóc Thiết bị dưới Distribution Shift – Le Nhut Thanh Quang</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-48cb5fd48e62f5012225c83f74b157d4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Le Nhut Thanh Quang</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../courses/index.html"> 
<span class="menu-text">Learning Space</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/lenhutthanhquang"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#bài-tập-cuối-khoá-machine-learning" id="toc-bài-tập-cuối-khoá-machine-learning" class="nav-link active" data-scroll-target="#bài-tập-cuối-khoá-machine-learning">Bài tập cuối khoá — Machine Learning</a></li>
  <li><a href="#bối-cảnh-mục-tiêu" id="toc-bối-cảnh-mục-tiêu" class="nav-link" data-scroll-target="#bối-cảnh-mục-tiêu">Bối cảnh &amp; Mục tiêu</a></li>
  <li><a href="#thiết-lập-môi-trường-nạp-dữ-liệu" id="toc-thiết-lập-môi-trường-nạp-dữ-liệu" class="nav-link" data-scroll-target="#thiết-lập-môi-trường-nạp-dữ-liệu">0. Thiết lập môi trường &amp; nạp dữ liệu</a></li>
  <li><a href="#phần-1-khám-phá-dữ-liệu-eda" id="toc-phần-1-khám-phá-dữ-liệu-eda" class="nav-link" data-scroll-target="#phần-1-khám-phá-dữ-liệu-eda">Phần 1 — Khám phá dữ liệu (EDA)</a>
  <ul class="collapse">
  <li><a href="#thống-kê-mô-tả-mức-mất-cân-bằng-của-biến-mục-tiêu" id="toc-thống-kê-mô-tả-mức-mất-cân-bằng-của-biến-mục-tiêu" class="nav-link" data-scroll-target="#thống-kê-mô-tả-mức-mất-cân-bằng-của-biến-mục-tiêu">1.1 Thống kê mô tả &amp; mức mất cân bằng của biến mục tiêu</a></li>
  <li><a href="#so-sánh-phân-phối-dây-chuyền-a-vs-b-dấu-hiệu-distribution-shift" id="toc-so-sánh-phân-phối-dây-chuyền-a-vs-b-dấu-hiệu-distribution-shift" class="nav-link" data-scroll-target="#so-sánh-phân-phối-dây-chuyền-a-vs-b-dấu-hiệu-distribution-shift">1.2 So sánh phân phối Dây chuyền A vs B — dấu hiệu Distribution Shift</a></li>
  <li><a href="#correlation-heatmap-feature-liên-quan-nguy-cơ-hỏng" id="toc-correlation-heatmap-feature-liên-quan-nguy-cơ-hỏng" class="nav-link" data-scroll-target="#correlation-heatmap-feature-liên-quan-nguy-cơ-hỏng">1.3 Correlation heatmap &amp; feature liên quan nguy cơ hỏng</a></li>
  <li><a href="#quan-hệ-giữa-biến-phân-loại-và-tỉ-lệ-hỏng" id="toc-quan-hệ-giữa-biến-phân-loại-và-tỉ-lệ-hỏng" class="nav-link" data-scroll-target="#quan-hệ-giữa-biến-phân-loại-và-tỉ-lệ-hỏng">1.4 Quan hệ giữa biến phân loại và tỉ lệ hỏng</a></li>
  </ul></li>
  <li><a href="#phần-2-tiền-xử-lý-feature-engineering" id="toc-phần-2-tiền-xử-lý-feature-engineering" class="nav-link" data-scroll-target="#phần-2-tiền-xử-lý-feature-engineering">Phần 2 — Tiền xử lý &amp; Feature Engineering</a>
  <ul class="collapse">
  <li><a href="#feature-engineering-biến-hoá-cơ-chế-hỏng-thành-đặc-trưng" id="toc-feature-engineering-biến-hoá-cơ-chế-hỏng-thành-đặc-trưng" class="nav-link" data-scroll-target="#feature-engineering-biến-hoá-cơ-chế-hỏng-thành-đặc-trưng">2.1 Feature Engineering — biến hoá cơ chế hỏng thành đặc trưng</a></li>
  <li><a href="#kiểm-chứng-tác-dụng-feature-mới" id="toc-kiểm-chứng-tác-dụng-feature-mới" class="nav-link" data-scroll-target="#kiểm-chứng-tác-dụng-feature-mới">2.2 Kiểm chứng tác dụng feature mới</a></li>
  <li><a href="#encoding-scaling-fit-chỉ-trên-train-xử-lý-imbalance" id="toc-encoding-scaling-fit-chỉ-trên-train-xử-lý-imbalance" class="nav-link" data-scroll-target="#encoding-scaling-fit-chỉ-trên-train-xử-lý-imbalance">2.3 Encoding, Scaling (fit chỉ trên Train) &amp; xử lý Imbalance</a></li>
  </ul></li>
  <li><a href="#phần-3-phát-hiện-xử-lý-distribution-shift" id="toc-phần-3-phát-hiện-xử-lý-distribution-shift" class="nav-link" data-scroll-target="#phần-3-phát-hiện-xử-lý-distribution-shift">Phần 3 — Phát hiện &amp; Xử lý Distribution Shift</a>
  <ul class="collapse">
  <li><a href="#psi-ks-test-cho-tất-cả-feature-số" id="toc-psi-ks-test-cho-tất-cả-feature-số" class="nav-link" data-scroll-target="#psi-ks-test-cho-tất-cả-feature-số">3.1 PSI &amp; KS-Test cho tất cả feature số</a></li>
  <li><a href="#drift-classifier-tìm-feature-thủ-phạm-gây-shift" id="toc-drift-classifier-tìm-feature-thủ-phạm-gây-shift" class="nav-link" data-scroll-target="#drift-classifier-tìm-feature-thủ-phạm-gây-shift">3.2 Drift Classifier — tìm feature ‘thủ phạm’ gây shift</a></li>
  <li><a href="#xử-lý-shift-importance-reweighting-threshold-calibration" id="toc-xử-lý-shift-importance-reweighting-threshold-calibration" class="nav-link" data-scroll-target="#xử-lý-shift-importance-reweighting-threshold-calibration">3.3 Xử lý shift: Importance Reweighting + Threshold Calibration</a></li>
  </ul></li>
  <li><a href="#phần-4-xây-dựng-mô-hình-đánh-giá" id="toc-phần-4-xây-dựng-mô-hình-đánh-giá" class="nav-link" data-scroll-target="#phần-4-xây-dựng-mô-hình-đánh-giá">Phần 4 — Xây dựng mô hình &amp; Đánh giá</a>
  <ul class="collapse">
  <li><a href="#hyperparameter-tuning-randomizedsearchcv-stratified-5-fold" id="toc-hyperparameter-tuning-randomizedsearchcv-stratified-5-fold" class="nav-link" data-scroll-target="#hyperparameter-tuning-randomizedsearchcv-stratified-5-fold">4.1 Hyperparameter Tuning (RandomizedSearchCV + Stratified 5-Fold)</a></li>
  <li><a href="#đánh-giá-đa-chiều-trên-test-dây-chuyền-b-bảng-so-sánh" id="toc-đánh-giá-đa-chiều-trên-test-dây-chuyền-b-bảng-so-sánh" class="nav-link" data-scroll-target="#đánh-giá-đa-chiều-trên-test-dây-chuyền-b-bảng-so-sánh">4.2 Đánh giá đa chiều trên Test (Dây chuyền B) &amp; bảng so sánh</a></li>
  <li><a href="#b-chẩn-đoán-hội-tụ-n_iter-randomizedsearchcv" id="toc-b-chẩn-đoán-hội-tụ-n_iter-randomizedsearchcv" class="nav-link" data-scroll-target="#b-chẩn-đoán-hội-tụ-n_iter-randomizedsearchcv">4.2b Chẩn đoán hội tụ n_iter (RandomizedSearchCV)</a></li>
  <li><a href="#chi-tiết-mô-hình-tốt-nhất-feature-importance-confusion-matrix" id="toc-chi-tiết-mô-hình-tốt-nhất-feature-importance-confusion-matrix" class="nav-link" data-scroll-target="#chi-tiết-mô-hình-tốt-nhất-feature-importance-confusion-matrix">4.3 Chi tiết mô hình tốt nhất: feature importance &amp; confusion matrix</a></li>
  </ul></li>
  <li><a href="#phần-5-báo-cáo-cuối-khoá" id="toc-phần-5-báo-cáo-cuối-khoá" class="nav-link" data-scroll-target="#phần-5-báo-cáo-cuối-khoá">Phần 5 — Báo cáo cuối khoá</a>
  <ul class="collapse">
  <li><a href="#tóm-tắt-phương-pháp" id="toc-tóm-tắt-phương-pháp" class="nav-link" data-scroll-target="#tóm-tắt-phương-pháp">5.1 Tóm tắt phương pháp</a></li>
  <li><a href="#kết-quả-chính" id="toc-kết-quả-chính" class="nav-link" data-scroll-target="#kết-quả-chính">5.2 Kết quả chính</a></li>
  <li><a href="#insight-vận-hành-bảo-trì" id="toc-insight-vận-hành-bảo-trì" class="nav-link" data-scroll-target="#insight-vận-hành-bảo-trì">5.3 Insight vận hành / bảo trì</a></li>
  <li><a href="#hạn-chế-hướng-cải-thiện" id="toc-hạn-chế-hướng-cải-thiện" class="nav-link" data-scroll-target="#hạn-chế-hướng-cải-thiện">5.4 Hạn chế &amp; hướng cải thiện</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Dự đoán Hỏng hóc Thiết bị dưới Distribution Shift</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="bài-tập-cuối-khoá-machine-learning" class="level3">
<h3 class="anchored" data-anchor-id="bài-tập-cuối-khoá-machine-learning">Bài tập cuối khoá — Machine Learning</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Họ tên</th>
<th>MSSV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nguyễn Huy Cường</td>
<td>25MS23319</td>
</tr>
<tr class="even">
<td>Lê Nhựt Thanh Quang</td>
<td>25MS23318</td>
</tr>
<tr class="odd">
<td>Hớn Vĩ Dân</td>
<td>25MS23316</td>
</tr>
<tr class="even">
<td>Nguyễn Đức Minh Khoa</td>
<td>25MS23333</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="bối-cảnh-mục-tiêu" class="level2">
<h2 class="anchored" data-anchor-id="bối-cảnh-mục-tiêu">Bối cảnh &amp; Mục tiêu</h2>
<p>Một nhà máy cơ khí vận hành đội máy phay <strong>CNC</strong>. Bộ phận bảo trì muốn dự đoán <strong>thiết bị sẽ hỏng trong ca sản xuất kế tiếp</strong> (bài toán <strong>phân loại nhị phân</strong>) để chuyển từ <em>bảo trì bị động</em> (chạy đến hỏng) sang <em>bảo trì chủ động</em> (predictive maintenance).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Tập</th>
<th>Dây chuyền</th>
<th>Đặc điểm</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Train</strong></td>
<td>Dây chuyền A</td>
<td>Nhà máy cũ, vận hành ổn định ~2 năm, cảm biến hiệu chỉnh chuẩn</td>
</tr>
<tr class="even">
<td><strong>Test</strong></td>
<td>Dây chuyền B</td>
<td>Nhà máy mới, khí hậu nóng hơn, cảm biến vừa hiệu chỉnh lại, chế độ tải khác</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Vấn đề cốt lõi — Distribution Shift:</strong> Train và Test đến từ hai điều kiện vận hành khác nhau. Cùng cơ chế vật lý gây hỏng, nhưng <strong>phân phối biến đầu vào bị dịch chuyển</strong>. Phải <em>phát hiện → định lượng → xử lý</em> shift để mô hình còn hoạt động tốt khi triển khai trên Dây chuyền B.</p>
</blockquote>
<p><strong>Pipeline:</strong> EDA → Tiền xử lý &amp; Feature Engineering → <strong>Phát hiện &amp; Xử lý Distribution Shift (trọng tâm)</strong> → Mô hình &amp; Đánh giá → Báo cáo.</p>
<p><strong>Các cơ chế hỏng cơ học tiềm ẩn</strong> (gợi ý của đề, định hướng Feature Engineering): hao mòn dao · tản nhiệt kém · quá tải công suất · quá tải căng thẳng (overstrain).</p>
</section>
<section id="thiết-lập-môi-trường-nạp-dữ-liệu" class="level2">
<h2 class="anchored" data-anchor-id="thiết-lập-môi-trường-nạp-dữ-liệu">0. Thiết lập môi trường &amp; nạp dữ liệu</h2>
<div id="a9e164e1" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T02:58:22.307233Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T02:58:22.307013Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T02:58:23.458699Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T02:58:23.458349Z&quot;}}" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.patches <span class="im">import</span> Patch</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings<span class="op">;</span> warnings.filterwarnings(<span class="st">'ignore'</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Sklearn</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sklearn</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> (StratifiedKFold, RandomizedSearchCV,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>                                     cross_val_predict, cross_val_score)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestClassifier, HistGradientBoostingClassifier</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.calibration <span class="im">import</span> CalibratedClassifierCV</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.feature_selection <span class="im">import</span> mutual_info_classif</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> (roc_auc_score, average_precision_score, f1_score,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>                             precision_recall_curve, roc_curve, confusion_matrix)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> ks_2samp, loguniform, randint</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> shap</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>RANDOM_STATE <span class="op">=</span> <span class="dv">42</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>np.random.seed(RANDOM_STATE)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">'whitegrid'</span>, context<span class="op">=</span><span class="st">'notebook'</span>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>plt.rcParams.update({<span class="st">'figure.dpi'</span>:<span class="dv">110</span>, <span class="st">'axes.titlesize'</span>:<span class="dv">11</span>, <span class="st">'font.size'</span>:<span class="dv">10</span>})</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>C_A, C_B, C_GREY <span class="op">=</span> <span class="st">'#4C72B0'</span>, <span class="st">'#C44E52'</span>, <span class="st">'#8C8C8C'</span>   <span class="co"># A(train), B(test), phụ</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Môi trường tái lập: người chấm đối chiếu phiên bản thư viện với requirements.txt</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'scikit-learn </span><span class="sc">{</span>sklearn<span class="sc">.</span>__version__<span class="sc">}</span><span class="ss"> | numpy </span><span class="sc">{</span>np<span class="sc">.</span>__version__<span class="sc">}</span><span class="ss"> | pandas </span><span class="sc">{</span>pd<span class="sc">.</span>__version__<span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>scikit-learn 1.9.0 | numpy 2.3.5 | pandas 2.3.3</code></pre>
</div>
</div>
<div id="c1436440" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T02:58:23.459920Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T02:58:23.459807Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T02:58:23.471626Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T02:58:23.471233Z&quot;}}" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Nạp dữ liệu — hai dây chuyền</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>train <span class="op">=</span> pd.read_csv(<span class="st">'data/train.csv'</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>test  <span class="op">=</span> pd.read_csv(<span class="st">'data/test.csv'</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>NUM <span class="op">=</span> [<span class="st">'nhiet_do_moi_truong'</span>,<span class="st">'nhiet_do_quy_trinh'</span>,<span class="st">'toc_do_quay'</span>,<span class="st">'momen_xoan'</span>,<span class="st">'do_mon_dao'</span>]</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>CAT <span class="op">=</span> [<span class="st">'loai_san_pham'</span>,<span class="st">'ca_lam_viec'</span>]</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>TARGET <span class="op">=</span> <span class="st">'hong_hoc'</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Train (Dây chuyền A): </span><span class="sc">{</span>train<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">  |  Test (Dây chuyền B): </span><span class="sc">{</span>test<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Số giá trị thiếu — train: </span><span class="sc">{</span>train<span class="sc">.</span>isnull()<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss">, test: </span><span class="sc">{</span>test<span class="sc">.</span>isnull()<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>train.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Train (Dây chuyền A): (14000, 8)  |  Test (Dây chuyền B): (6000, 8)
Số giá trị thiếu — train: 0, test: 0</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">nhiet_do_moi_truong</th>
<th data-quarto-table-cell-role="th">nhiet_do_quy_trinh</th>
<th data-quarto-table-cell-role="th">toc_do_quay</th>
<th data-quarto-table-cell-role="th">momen_xoan</th>
<th data-quarto-table-cell-role="th">do_mon_dao</th>
<th data-quarto-table-cell-role="th">loai_san_pham</th>
<th data-quarto-table-cell-role="th">ca_lam_viec</th>
<th data-quarto-table-cell-role="th">hong_hoc</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>301.21</td>
<td>311.80</td>
<td>1864.3</td>
<td>47.52</td>
<td>210.9</td>
<td>H</td>
<td>Chiều</td>
<td>0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>302.66</td>
<td>311.52</td>
<td>1727.1</td>
<td>49.32</td>
<td>175.7</td>
<td>L</td>
<td>Đêm</td>
<td>0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>300.39</td>
<td>312.23</td>
<td>1516.6</td>
<td>42.70</td>
<td>54.5</td>
<td>L</td>
<td>Sáng</td>
<td>0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>298.27</td>
<td>308.38</td>
<td>1555.3</td>
<td>23.12</td>
<td>247.7</td>
<td>M</td>
<td>Sáng</td>
<td>1</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>301.02</td>
<td>310.22</td>
<td>1356.7</td>
<td>39.02</td>
<td>30.4</td>
<td>M</td>
<td>Đêm</td>
<td>0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<hr>
</section>
<section id="phần-1-khám-phá-dữ-liệu-eda" class="level1">
<h1>Phần 1 — Khám phá dữ liệu (EDA)</h1>
<p>Ba nhiệm vụ: (1) thống kê mô tả + kiểm tra imbalance của target; (2) so sánh trực quan phân phối A vs B để phát hiện shift; (3) correlation heatmap và nhận xét feature liên quan nguy cơ hỏng.</p>
<section id="thống-kê-mô-tả-mức-mất-cân-bằng-của-biến-mục-tiêu" class="level3">
<h3 class="anchored" data-anchor-id="thống-kê-mô-tả-mức-mất-cân-bằng-của-biến-mục-tiêu">1.1 Thống kê mô tả &amp; mức mất cân bằng của biến mục tiêu</h3>
<div id="d0ddc481" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T02:58:23.472830Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T02:58:23.472768Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T02:58:23.480800Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T02:58:23.480483Z&quot;}}" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>display(train[NUM].describe().T[[<span class="st">'mean'</span>,<span class="st">'std'</span>,<span class="st">'min'</span>,<span class="st">'25%'</span>,<span class="st">'50%'</span>,<span class="st">'75%'</span>,<span class="st">'max'</span>]].<span class="bu">round</span>(<span class="dv">2</span>))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Phân bố biến phân loại (train):'</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> c <span class="kw">in</span> CAT:</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'  </span><span class="sc">{</span>c<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>train[c]<span class="sc">.</span>value_counts()<span class="sc">.</span>to_dict()<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Tỉ lệ hỏng — Train: </span><span class="sc">{</span>train[TARGET]<span class="sc">.</span>mean()<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%  |  Test: </span><span class="sc">{</span>test[TARGET]<span class="sc">.</span>mean()<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">std</th>
<th data-quarto-table-cell-role="th">min</th>
<th data-quarto-table-cell-role="th">25%</th>
<th data-quarto-table-cell-role="th">50%</th>
<th data-quarto-table-cell-role="th">75%</th>
<th data-quarto-table-cell-role="th">max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">nhiet_do_moi_truong</th>
<td>299.99</td>
<td>1.99</td>
<td>292.00</td>
<td>298.64</td>
<td>300.00</td>
<td>301.35</td>
<td>307.54</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">nhiet_do_quy_trinh</th>
<td>309.98</td>
<td>2.23</td>
<td>300.99</td>
<td>308.46</td>
<td>309.96</td>
<td>311.49</td>
<td>318.86</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">toc_do_quay</th>
<td>1540.26</td>
<td>174.64</td>
<td>1180.00</td>
<td>1417.18</td>
<td>1537.35</td>
<td>1659.50</td>
<td>2153.50</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">momen_xoan</th>
<td>39.94</td>
<td>9.96</td>
<td>3.50</td>
<td>33.30</td>
<td>39.89</td>
<td>46.66</td>
<td>76.02</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">do_mon_dao</th>
<td>126.95</td>
<td>72.69</td>
<td>0.00</td>
<td>64.50</td>
<td>126.20</td>
<td>190.10</td>
<td>253.00</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Phân bố biến phân loại (train):
  loai_san_pham: {'L': 7022, 'M': 4204, 'H': 2774}
  ca_lam_viec: {'Sáng': 5675, 'Chiều': 4792, 'Đêm': 3533}

Tỉ lệ hỏng — Train: 7.36%  |  Test: 7.95%</code></pre>
</div>
</div>
<div id="5afe1e9e" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T02:58:23.481870Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T02:58:23.481783Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T02:58:23.568691Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T02:58:23.568377Z&quot;}}" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="fl">3.2</span>))</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, (df, name) <span class="kw">in</span> <span class="bu">zip</span>(axes, [(train,<span class="st">'Dây chuyền A (Train)'</span>),(test,<span class="st">'Dây chuyền B (Test)'</span>)]):</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    vc <span class="op">=</span> df[TARGET].value_counts().sort_index()<span class="op">;</span> rate <span class="op">=</span> df[TARGET].mean()<span class="op">*</span><span class="dv">100</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    bars <span class="op">=</span> ax.bar([<span class="st">'Bình thường (0)'</span>,<span class="st">'Hỏng (1)'</span>], vc.values, color<span class="op">=</span>[C_A, C_B])</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> b,v <span class="kw">in</span> <span class="bu">zip</span>(bars, vc.values):</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>        ax.text(b.get_x()<span class="op">+</span>b.get_width()<span class="op">/</span><span class="dv">2</span>, v, <span class="ss">f'</span><span class="sc">{</span>v<span class="sc">:,}</span><span class="ss">'</span>, ha<span class="op">=</span><span class="st">'center'</span>, va<span class="op">=</span><span class="st">'bottom'</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f'</span><span class="sc">{</span>name<span class="sc">}</span><span class="ch">\n</span><span class="ss">tỉ lệ hỏng = </span><span class="sc">{</span>rate<span class="sc">:.1f}</span><span class="ss">%'</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">'Số mẫu'</span>)<span class="op">;</span> ax.margins(y<span class="op">=</span><span class="fl">0.15</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">'Biến mục tiêu mất cân bằng mạnh (lớp thiểu số ~7–8%)'</span>, y<span class="op">=</span><span class="fl">1.02</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="CNC_Failure_Distribution_Shift_files/figure-html/cell-5-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Nhận xét 1.1.</strong> Lớp <em>hỏng</em> chỉ chiếm <strong>~7.4%</strong> (train) và <strong>~8.0%</strong> (test) → mất cân bằng mạnh. Hệ quả: <strong>accuracy vô nghĩa</strong> (đoán “không hỏng” đã đạt &gt;92%); phải dùng <strong>AUC-PR, F1, Precision-Recall</strong> và xử lý imbalance bằng <code>class_weight</code>/SMOTE.</p>
</section>
<section id="so-sánh-phân-phối-dây-chuyền-a-vs-b-dấu-hiệu-distribution-shift" class="level3">
<h3 class="anchored" data-anchor-id="so-sánh-phân-phối-dây-chuyền-a-vs-b-dấu-hiệu-distribution-shift">1.2 So sánh phân phối Dây chuyền A vs B — dấu hiệu Distribution Shift</h3>
<div id="94d847c1" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T02:58:23.569976Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T02:58:23.569906Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T02:58:23.906368Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T02:58:23.905945Z&quot;}}" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> {<span class="st">'nhiet_do_moi_truong'</span>:<span class="st">'Nhiệt độ môi trường (K)'</span>,<span class="st">'nhiet_do_quy_trinh'</span>:<span class="st">'Nhiệt độ quy trình (K)'</span>,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>          <span class="st">'toc_do_quay'</span>:<span class="st">'Tốc độ quay (rpm)'</span>,<span class="st">'momen_xoan'</span>:<span class="st">'Mômen xoắn (Nm)'</span>,<span class="st">'do_mon_dao'</span>:<span class="st">'Độ mòn dao (phút)'</span>}</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="fl">6.2</span>))<span class="op">;</span> axes <span class="op">=</span> axes.ravel()</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, col <span class="kw">in</span> <span class="bu">zip</span>(axes, NUM):</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    sns.kdeplot(train[col], ax<span class="op">=</span>ax, color<span class="op">=</span>C_A, fill<span class="op">=</span><span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.35</span>, lw<span class="op">=</span><span class="fl">1.6</span>, label<span class="op">=</span><span class="st">'A (Train)'</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    sns.kdeplot(test[col],  ax<span class="op">=</span>ax, color<span class="op">=</span>C_B, fill<span class="op">=</span><span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.35</span>, lw<span class="op">=</span><span class="fl">1.6</span>, label<span class="op">=</span><span class="st">'B (Test)'</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    ax.axvline(train[col].mean(), color<span class="op">=</span>C_A, ls<span class="op">=</span><span class="st">'--'</span>, lw<span class="op">=</span><span class="dv">1</span>)<span class="op">;</span> ax.axvline(test[col].mean(), color<span class="op">=</span>C_B, ls<span class="op">=</span><span class="st">'--'</span>, lw<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f'</span><span class="sc">{</span>labels[col]<span class="sc">}</span><span class="ch">\n</span><span class="ss">'</span> <span class="op">+</span> <span class="vs">r'</span><span class="dv">$\D</span><span class="vs">elta</span><span class="dv">$</span><span class="vs">mean = '</span> <span class="op">+</span> <span class="ss">f'</span><span class="sc">{</span>test[col]<span class="sc">.</span>mean()<span class="op">-</span>train[col]<span class="sc">.</span>mean()<span class="sc">:+.1f}</span><span class="ss">'</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">''</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">''</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">8</span>)<span class="op">;</span> axes[<span class="op">-</span><span class="dv">1</span>].axis(<span class="st">'off'</span>)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">'Distribution shift: Dây chuyền B nóng hơn &amp; quay nhanh hơn Dây chuyền A'</span>, y<span class="op">=</span><span class="fl">1.0</span>)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="CNC_Failure_Distribution_Shift_files/figure-html/cell-6-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Nhận xét 1.2.</strong> Dấu hiệu shift rất rõ, đúng bối cảnh “nhà máy B nóng hơn, tải khác”: - <strong>Nhiệt độ môi trường +2.5K</strong>, <strong>nhiệt độ quy trình +1.9K</strong> → dịch phải mạnh. - <strong>Tốc độ quay +70 rpm</strong> → B chạy nhanh hơn. - <strong>Mômen xoắn −3.4 Nm</strong> → B tải nhẹ hơn đôi chút. - <strong>Độ mòn dao</strong> gần như trùng khớp → biến này <strong>ổn định</strong> giữa hai dây chuyền.</p>
<p>→ Đây là <strong>covariate shift</strong> (P(X) đổi). Phần 3 sẽ định lượng chính xác bằng PSI/KS và drift classifier.</p>
</section>
<section id="correlation-heatmap-feature-liên-quan-nguy-cơ-hỏng" class="level3">
<h3 class="anchored" data-anchor-id="correlation-heatmap-feature-liên-quan-nguy-cơ-hỏng">1.3 Correlation heatmap &amp; feature liên quan nguy cơ hỏng</h3>
<div id="67e6e769" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T02:58:23.907536Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T02:58:23.907450Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T02:58:24.000649Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T02:58:24.000204Z&quot;}}" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>short <span class="op">=</span> {<span class="st">'nhiet_do_moi_truong'</span>:<span class="st">'Nhiệt độ MT'</span>,<span class="st">'nhiet_do_quy_trinh'</span>:<span class="st">'Nhiệt độ QT'</span>,<span class="st">'toc_do_quay'</span>:<span class="st">'Tốc độ quay'</span>,</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>         <span class="st">'momen_xoan'</span>:<span class="st">'Mômen'</span>,<span class="st">'do_mon_dao'</span>:<span class="st">'Độ mòn dao'</span>,<span class="st">'hong_hoc'</span>:<span class="st">'HỎNG HÓC'</span>}</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>corr <span class="op">=</span> train[NUM<span class="op">+</span>[TARGET]].rename(columns<span class="op">=</span>short).corr()</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">6.2</span>, <span class="dv">5</span>))</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>sns.heatmap(corr, annot<span class="op">=</span><span class="va">True</span>, fmt<span class="op">=</span><span class="st">'.2f'</span>, cmap<span class="op">=</span><span class="st">'RdBu_r'</span>, center<span class="op">=</span><span class="dv">0</span>, vmin<span class="op">=-</span><span class="dv">1</span>, vmax<span class="op">=</span><span class="dv">1</span>, square<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>            linewidths<span class="op">=</span><span class="fl">0.5</span>, cbar_kws<span class="op">=</span>{<span class="st">'label'</span>:<span class="st">'Pearson r'</span>,<span class="st">'shrink'</span>:<span class="fl">0.8</span>}, ax<span class="op">=</span>ax, annot_kws<span class="op">=</span>{<span class="st">'fontsize'</span>:<span class="dv">8</span>})</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Tương quan giữa các biến số (Dây chuyền A)'</span>)<span class="op">;</span> fig.tight_layout()<span class="op">;</span> plt.show()</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Tương quan tuyến tính với hong_hoc:'</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(train[NUM].corrwith(train[TARGET]).<span class="bu">round</span>(<span class="dv">3</span>).sort_values(key<span class="op">=</span><span class="bu">abs</span>, ascending<span class="op">=</span><span class="va">False</span>).to_string())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="CNC_Failure_Distribution_Shift_files/figure-html/cell-7-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Tương quan tuyến tính với hong_hoc:
do_mon_dao             0.195
toc_do_quay           -0.066
nhiet_do_quy_trinh    -0.033
momen_xoan            -0.006
nhiet_do_moi_truong    0.001</code></pre>
</div>
</div>
<p><strong>Nhận xét 1.3.</strong> - <code>do_mon_dao</code> có tương quan tuyến tính cao nhất với hỏng (<strong>r ≈ 0.20</strong>) — dao mòn lâu → dễ hỏng. - Hai biến nhiệt độ tương quan chặt với nhau (<strong>r ≈ 0.89</strong>) vì nhiệt quy trình sinh ra từ nhiệt môi trường. - Các tương quan tuyến tính còn lại <strong>rất yếu</strong>. Điều này <em>không</em> nghĩa là biến vô dụng: cơ chế hỏng cơ học là <strong>phi tuyến &amp; tương tác</strong> (VD hỏng khi <em>mômen cao ĐỒNG THỜI tốc độ thấp</em>). Đây chính là lý do <strong>Feature Engineering</strong> (Phần 2) và <strong>mô hình phi tuyến</strong> (Phần 4) là cần thiết.</p>
</section>
<section id="quan-hệ-giữa-biến-phân-loại-và-tỉ-lệ-hỏng" class="level3">
<h3 class="anchored" data-anchor-id="quan-hệ-giữa-biến-phân-loại-và-tỉ-lệ-hỏng">1.4 Quan hệ giữa biến phân loại và tỉ lệ hỏng</h3>
<div id="732832b0" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T02:58:24.001843Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T02:58:24.001785Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T02:58:24.072539Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T02:58:24.072150Z&quot;}}" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">3.2</span>))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, col <span class="kw">in</span> <span class="bu">zip</span>(axes, CAT):</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    rate <span class="op">=</span> train.groupby(col)[TARGET].mean().mul(<span class="dv">100</span>).sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    bars <span class="op">=</span> ax.bar(rate.index.astype(<span class="bu">str</span>), rate.values, color<span class="op">=</span>C_B, alpha<span class="op">=</span><span class="fl">0.85</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    ax.axhline(train[TARGET].mean()<span class="op">*</span><span class="dv">100</span>, color<span class="op">=</span>C_GREY, ls<span class="op">=</span><span class="st">'--'</span>, lw<span class="op">=</span><span class="dv">1</span>, label<span class="op">=</span><span class="st">'TB toàn tập'</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> b,v <span class="kw">in</span> <span class="bu">zip</span>(bars, rate.values):</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>        ax.text(b.get_x()<span class="op">+</span>b.get_width()<span class="op">/</span><span class="dv">2</span>, v, <span class="ss">f'</span><span class="sc">{</span>v<span class="sc">:.1f}</span><span class="ss">%'</span>, ha<span class="op">=</span><span class="st">'center'</span>, va<span class="op">=</span><span class="st">'bottom'</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f'Tỉ lệ hỏng theo </span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">'</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">'Tỉ lệ hỏng (%)'</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    ax.margins(y<span class="op">=</span><span class="fl">0.18</span>)<span class="op">;</span> ax.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">'Biến phân loại chỉ tạo khác biệt nhỏ (~0.7 điểm %)'</span>, y<span class="op">=</span><span class="fl">1.02</span>)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="CNC_Failure_Distribution_Shift_files/figure-html/cell-8-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Nhận xét 1.4.</strong> Sản phẩm hạng <strong>L</strong> và ca <strong>Đêm</strong> có tỉ lệ hỏng nhỉnh hơn, nhưng chênh lệch chỉ ~0.7 điểm phần trăm → tín hiệu yếu. Vẫn giữ lại (one-hot) làm biến bổ trợ.</p>
<hr>
</section>
</section>
<section id="phần-2-tiền-xử-lý-feature-engineering" class="level1">
<h1>Phần 2 — Tiền xử lý &amp; Feature Engineering</h1>
<p>Ba nhiệm vụ: (1) scaling + encoding + xử lý imbalance; (2) <strong>fit scaler CHỈ trên Train</strong> rồi transform cả hai (chống rò rỉ dữ liệu Test); (3) tạo ≥2 feature cơ học mới và kiểm chứng tác dụng.</p>
<section id="feature-engineering-biến-hoá-cơ-chế-hỏng-thành-đặc-trưng" class="level3">
<h3 class="anchored" data-anchor-id="feature-engineering-biến-hoá-cơ-chế-hỏng-thành-đặc-trưng">2.1 Feature Engineering — biến hoá cơ chế hỏng thành đặc trưng</h3>
<p>Mỗi feature mới ánh xạ trực tiếp một <strong>cơ chế hỏng vật lý</strong> trong gợi ý của đề:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Feature mới</th>
<th>Công thức</th>
<th>Cơ chế hỏng</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>chenh_lech_nhiet</code></td>
<td><code>nhiet_do_quy_trinh − nhiet_do_moi_truong</code></td>
<td><strong>Tản nhiệt kém</strong> — chênh lệch <strong>nhỏ</strong> = nhiệt bị giữ lại trong máy, không thoát ra được → nguy cơ hỏng cao</td>
</tr>
<tr class="even">
<td><code>cong_suat_co</code></td>
<td><code>momen_xoan × (toc_do_quay·2π/60)</code> (Watt)</td>
<td><strong>Quá tải công suất</strong> — công suất cơ = mômen × tốc độ góc</td>
</tr>
<tr class="odd">
<td><code>tich_mon_momen</code></td>
<td><code>do_mon_dao × momen_xoan</code></td>
<td><strong>Quá tải căng thẳng</strong> — dao mòn chịu mômen lớn = ứng suất cao</td>
</tr>
<tr class="even">
<td><code>strain_index</code></td>
<td><code>do_mon_dao × momen_xoan / toc_do_quay</code></td>
<td><strong>Overstrain</strong> — mômen/mòn cao ở tốc độ thấp = nguy hiểm nhất</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Lưu ý chiều tác động của <code>chenh_lech_nhiet</code>:</strong> dòng nhiệt thoát khỏi máy tỉ lệ thuận với ΔT (định luật truyền nhiệt), nên ΔT <strong>nhỏ bất thường</strong> nghĩa là môi trường nóng gần bằng điểm gia công — nhiệt không có đường thoát. Bảng ngũ phân vị ở mục 2.2 kiểm chứng đúng chiều này: nhóm ΔT <strong>thấp nhất</strong> có tỉ lệ hỏng 11.7% so với ~6% các nhóm còn lại.</p>
</blockquote>
<div id="a324cbf4" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T02:58:24.073679Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T02:58:24.073618Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T02:58:24.077474Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T02:58:24.077146Z&quot;}}" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> add_features(df):</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    d <span class="op">=</span> df.copy()</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    d[<span class="st">'chenh_lech_nhiet'</span>] <span class="op">=</span> d[<span class="st">'nhiet_do_quy_trinh'</span>] <span class="op">-</span> d[<span class="st">'nhiet_do_moi_truong'</span>]   <span class="co"># ΔT nhỏ = nhiệt kẹt trong máy (tản nhiệt kém)</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    d[<span class="st">'cong_suat_co'</span>]     <span class="op">=</span> d[<span class="st">'momen_xoan'</span>] <span class="op">*</span> d[<span class="st">'toc_do_quay'</span>] <span class="op">*</span> <span class="dv">2</span><span class="op">*</span>np.pi<span class="op">/</span><span class="dv">60</span>      <span class="co"># P = τ·ω (Watt); 2π/60 đổi rpm -&gt; rad/s</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    d[<span class="st">'tich_mon_momen'</span>]   <span class="op">=</span> d[<span class="st">'do_mon_dao'</span>] <span class="op">*</span> d[<span class="st">'momen_xoan'</span>]                    <span class="co"># tích mã hoá chữ "VÀ": chỉ lớn khi mòn VÀ mômen cùng lớn</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    d[<span class="st">'strain_index'</span>]     <span class="op">=</span> d[<span class="st">'do_mon_dao'</span>] <span class="op">*</span> d[<span class="st">'momen_xoan'</span>] <span class="op">/</span> (d[<span class="st">'toc_do_quay'</span>] <span class="op">+</span> <span class="fl">1e-6</span>)  <span class="co"># +1e-6 chống chia 0</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> d</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>FE <span class="op">=</span> [<span class="st">'chenh_lech_nhiet'</span>,<span class="st">'cong_suat_co'</span>,<span class="st">'tich_mon_momen'</span>,<span class="st">'strain_index'</span>]</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>ALL_NUM <span class="op">=</span> NUM <span class="op">+</span> FE</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>train_fe <span class="op">=</span> add_features(train)<span class="op">;</span> test_fe <span class="op">=</span> add_features(test)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Đã tạo'</span>, <span class="bu">len</span>(FE), <span class="st">'feature mới:'</span>, FE)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Đã tạo 4 feature mới: ['chenh_lech_nhiet', 'cong_suat_co', 'tich_mon_momen', 'strain_index']</code></pre>
</div>
</div>
</section>
<section id="kiểm-chứng-tác-dụng-feature-mới" class="level3">
<h3 class="anchored" data-anchor-id="kiểm-chứng-tác-dụng-feature-mới">2.2 Kiểm chứng tác dụng feature mới</h3>
<div id="d7da5c6e" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T02:58:24.078510Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T02:58:24.078456Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T02:58:24.293086Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T02:58:24.292732Z&quot;}}" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># (a) Trực quan: phân phối feature mới theo nhãn hỏng</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>fe_labels <span class="op">=</span> {<span class="st">'chenh_lech_nhiet'</span>:<span class="st">'Chênh lệch nhiệt (K)'</span>,<span class="st">'cong_suat_co'</span>:<span class="st">'Công suất cơ (W)'</span>,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>             <span class="st">'tich_mon_momen'</span>:<span class="st">'Mòn × Mômen'</span>,<span class="st">'strain_index'</span>:<span class="st">'Chỉ số quá tải (strain)'</span>}</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">4</span>, figsize<span class="op">=</span>(<span class="dv">13</span>, <span class="dv">3</span>))</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, col <span class="kw">in</span> <span class="bu">zip</span>(axes, FE):</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> lab, c, name <span class="kw">in</span> [(<span class="dv">0</span>,C_A,<span class="st">'Bình thường'</span>),(<span class="dv">1</span>,C_B,<span class="st">'Hỏng'</span>)]:</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>        sns.kdeplot(train_fe.loc[train_fe[TARGET]<span class="op">==</span>lab, col], ax<span class="op">=</span>ax, color<span class="op">=</span>c, fill<span class="op">=</span><span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.35</span>, lw<span class="op">=</span><span class="fl">1.4</span>, label<span class="op">=</span>name)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    ax.set_title(fe_labels[col], fontsize<span class="op">=</span><span class="dv">9</span>)<span class="op">;</span> ax.set_xlabel(<span class="st">''</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">''</span>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">8</span>)<span class="op">;</span> axes[<span class="dv">0</span>].set_ylabel(<span class="st">'Mật độ'</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">'Feature cơ học mới: nhóm HỎNG lệch rõ ở "Mòn×Mômen" và "Chỉ số quá tải"'</span>, y<span class="op">=</span><span class="fl">1.03</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="CNC_Failure_Distribution_Shift_files/figure-html/cell-10-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="60be5158" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T02:58:24.294141Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T02:58:24.294083Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T02:58:24.303920Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T02:58:24.303590Z&quot;}}" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># (b) Bằng chứng cơ chế: tỉ lệ hỏng (%) theo ngũ phân vị của từng feature mới — đọc được "chiều" của nguy cơ</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co">#     Q1 = 20% giá trị thấp nhất … Q5 = 20% cao nhất (chia bin trên train)</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>quints <span class="op">=</span> [<span class="st">'Q1 (thấp nhất)'</span>,<span class="st">'Q2'</span>,<span class="st">'Q3'</span>,<span class="st">'Q4'</span>,<span class="st">'Q5 (cao nhất)'</span>]</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>quint_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    col: train_fe.groupby(pd.qcut(train_fe[col], <span class="dv">5</span>, labels<span class="op">=</span>quints), observed<span class="op">=</span><span class="va">True</span>)[TARGET].mean().mul(<span class="dv">100</span>).<span class="bu">round</span>(<span class="dv">1</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> col <span class="kw">in</span> FE</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>}).T</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>quint_df.index.name <span class="op">=</span> <span class="st">'Tỉ lệ hỏng (%)'</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>display(quint_df)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Tỉ lệ hỏng nền (toàn train): </span><span class="sc">{</span>train_fe[TARGET]<span class="sc">.</span>mean()<span class="op">*</span><span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Q1 (thấp nhất)</th>
<th data-quarto-table-cell-role="th">Q2</th>
<th data-quarto-table-cell-role="th">Q3</th>
<th data-quarto-table-cell-role="th">Q4</th>
<th data-quarto-table-cell-role="th">Q5 (cao nhất)</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Tỉ lệ hỏng (%)</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">chenh_lech_nhiet</th>
<td>11.7</td>
<td>5.8</td>
<td>6.3</td>
<td>6.4</td>
<td>6.5</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">cong_suat_co</th>
<td>10.5</td>
<td>6.7</td>
<td>5.7</td>
<td>5.4</td>
<td>8.6</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">tich_mon_momen</th>
<td>5.7</td>
<td>4.7</td>
<td>4.0</td>
<td>5.3</td>
<td>17.2</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">strain_index</th>
<td>5.2</td>
<td>4.6</td>
<td>4.1</td>
<td>5.6</td>
<td>17.2</td>
</tr>
</tbody>
</table>

</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Tỉ lệ hỏng nền (toàn train): 7.4%</code></pre>
</div>
</div>
<div id="87122840" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T02:58:24.304915Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T02:58:24.304861Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T02:58:26.791306Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T02:58:26.790621Z&quot;}}" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># (c) Định lượng: AUC-PR (5-fold CV) trước/sau khi thêm feature + Mutual Information</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>skf <span class="op">=</span> StratifiedKFold(<span class="dv">5</span>, shuffle<span class="op">=</span><span class="va">True</span>, random_state<span class="op">=</span>RANDOM_STATE)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> train_fe[TARGET].values</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>auc_base <span class="op">=</span> cross_val_score(HistGradientBoostingClassifier(random_state<span class="op">=</span>RANDOM_STATE),</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>                           train[NUM].values, y, cv<span class="op">=</span>skf, scoring<span class="op">=</span><span class="st">'average_precision'</span>).mean()</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>auc_aug  <span class="op">=</span> cross_val_score(HistGradientBoostingClassifier(random_state<span class="op">=</span>RANDOM_STATE),</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>                           train_fe[ALL_NUM].values, y, cv<span class="op">=</span>skf, scoring<span class="op">=</span><span class="st">'average_precision'</span>).mean()</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'AUC-PR (CV) chỉ feature gốc : </span><span class="sc">{</span>auc_base<span class="sc">:.4f}</span><span class="ss">'</span>)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'AUC-PR (CV) + feature mới   : </span><span class="sc">{</span>auc_aug<span class="sc">:.4f}</span><span class="ss">   (cải thiện </span><span class="sc">{</span>auc_aug<span class="op">-</span>auc_base<span class="sc">:+.4f}</span><span class="ss">)'</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>mi <span class="op">=</span> pd.Series(mutual_info_classif(train_fe[ALL_NUM], y, random_state<span class="op">=</span>RANDOM_STATE), index<span class="op">=</span>ALL_NUM)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">Mutual Information với target (top):'</span>)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(mi.sort_values(ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">6</span>).<span class="bu">round</span>(<span class="dv">4</span>).to_string())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>AUC-PR (CV) chỉ feature gốc : 0.6217
AUC-PR (CV) + feature mới   : 0.6451   (cải thiện +0.0234)

Mutual Information với target (top):
do_mon_dao          0.0614
tich_mon_momen      0.0258
cong_suat_co        0.0236
momen_xoan          0.0214
strain_index        0.0202
chenh_lech_nhiet    0.0105</code></pre>
</div>
</div>
<p><strong>Nhận xét 2.2.</strong> Feature mới có giá trị thực, kiểm chứng bằng 3 con đường độc lập: - <strong>Trực quan (a):</strong> phân phối <code>tich_mon_momen</code> và <code>strain_index</code> của nhóm <strong>hỏng</strong> dịch hẳn sang phải/lưỡng đỉnh — tách khỏi nhóm bình thường. - <strong>Bảng ngũ phân vị (b)</strong> xác nhận đúng “chiều” của từng cơ chế: <code>tich_mon_momen</code>/<code>strain_index</code> nguy hiểm ở <strong>Q5</strong> (~17% hỏng — gấp hơn 2 lần mức nền 7.4%); <code>cong_suat_co</code> nguy hiểm ở <strong>cả hai cực</strong> (quan hệ <strong>chữ U</strong>: quá thấp = máy “gằn” — mômen lớn nhưng quay chậm; quá cao = vượt ngưỡng thiết kế); riêng <code>chenh_lech_nhiet</code> nguy hiểm ở <strong>Q1</strong> — <strong>ΔT thấp = nhiệt bị giữ lại trong máy, tản nhiệt kém</strong> (11.7% so với ~6% các nhóm còn lại). Quan hệ chữ U và “nguy hiểm ở cực thấp” là thứ tương quan Pearson (≈0) hoàn toàn bỏ sót. - <strong>Định lượng (c):</strong> thêm feature mới <strong>tăng AUC-PR (CV) ~+0.023</strong>; về Mutual Information, <code>tich_mon_momen</code>, <code>cong_suat_co</code>, <code>strain_index</code> đều lọt <strong>top</strong> — bắt được thông tin phi tuyến mà tương quan tuyến tính không thấy.</p>
<blockquote class="blockquote">
<p><strong>Kết quả âm (feature ứng viên bị loại).</strong> Nhóm đã thử thêm 2 ứng viên: cờ nhị phân <code>do_mon_dao &gt; 200</code> và tỉ số <code>momen_xoan / toc_do_quay</code>, nhưng <strong>loại theo đúng giao thức kiểm chứng</strong>: cải thiện CV chỉ +0.003 (mức nhiễu — mô hình cây tự học được điểm cắt ~200 từ biến gốc), tỉ số mômen/tốc độ có <strong>PSI 0.225</strong> (không kháng shift do tốc độ và mômen ở Dây chuyền B dịch cùng chiều trong phép chia) và trùng lặp thông tin với <code>strain_index</code>. Nguyên tắc: <em>feature chỉ được nhận khi vừa cải thiện CV vừa không phá tính kháng shift.</em></p>
</blockquote>
</section>
<section id="encoding-scaling-fit-chỉ-trên-train-xử-lý-imbalance" class="level3">
<h3 class="anchored" data-anchor-id="encoding-scaling-fit-chỉ-trên-train-xử-lý-imbalance">2.3 Encoding, Scaling (fit chỉ trên Train) &amp; xử lý Imbalance</h3>
<div id="62aa8641" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T02:58:26.792996Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T02:58:26.792895Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T02:58:26.804437Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T02:58:26.803958Z&quot;}}" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One-hot encode biến phân loại. drop_first=True: bỏ 1 cột vì nó suy ra được từ các cột còn lại</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (tổng = 1) — tránh "bẫy biến giả"/đa cộng tuyến hoàn hảo gây bất ổn cho mô hình tuyến tính.</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> encode(df): <span class="cf">return</span> pd.get_dummies(df[CAT], prefix<span class="op">=</span>CAT, drop_first<span class="op">=</span><span class="va">True</span>).astype(<span class="bu">float</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>train_cat <span class="op">=</span> encode(train_fe)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>test_cat  <span class="op">=</span> encode(test_fe).reindex(columns<span class="op">=</span>train_cat.columns, fill_value<span class="op">=</span><span class="fl">0.0</span>)  <span class="co"># canh cột giống train</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>Xtr_raw <span class="op">=</span> pd.concat([train_fe[ALL_NUM].reset_index(drop<span class="op">=</span><span class="va">True</span>), train_cat.reset_index(drop<span class="op">=</span><span class="va">True</span>)], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>Xte_raw <span class="op">=</span> pd.concat([test_fe[ALL_NUM].reset_index(drop<span class="op">=</span><span class="va">True</span>),  test_cat.reset_index(drop<span class="op">=</span><span class="va">True</span>)], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>ytr, yte <span class="op">=</span> train_fe[TARGET].values, test_fe[TARGET].values</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="co"># ⚠️ CHỐNG RÒ RỈ: StandardScaler FIT CHỈ TRÊN TRAIN, rồi transform cả train và test</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="co"># (Mô hình cây không cần scaling — bất biến với biến đổi đơn điệu; nhưng LogisticRegression cần để hội tụ</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="co">#  và so sánh hệ số. Scale chung một lần để cả 3 mô hình ở Phần 4 dùng cùng một không gian feature.)</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>scaler <span class="op">=</span> StandardScaler().fit(Xtr_raw[ALL_NUM])</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>Xtr, Xte <span class="op">=</span> Xtr_raw.copy(), Xte_raw.copy()</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>Xtr[ALL_NUM] <span class="op">=</span> scaler.transform(Xtr_raw[ALL_NUM])</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>Xte[ALL_NUM] <span class="op">=</span> scaler.transform(Xte_raw[ALL_NUM])</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>FEATURES <span class="op">=</span> <span class="bu">list</span>(Xtr.columns)</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Bộ feature cuối (</span><span class="sc">{</span><span class="bu">len</span>(FEATURES)<span class="sc">}</span><span class="ss">):'</span>, FEATURES)</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Bằng chứng KHÔNG rò rỉ + shift còn hiện diện: train scaled mean ≈ 0, test scaled mean ≠ 0</span></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="ch">\n</span><span class="ss">|mean| train sau scale (≈0): </span><span class="sc">{</span>Xtr[ALL_NUM]<span class="sc">.</span>mean()<span class="sc">.</span><span class="bu">abs</span>()<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.4f}</span><span class="ss">'</span>)</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'mean test sau scale (lệch khỏi 0 = shift):'</span>)</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(Xte[ALL_NUM].mean().<span class="bu">round</span>(<span class="dv">3</span>).sort_values(key<span class="op">=</span><span class="bu">abs</span>, ascending<span class="op">=</span><span class="va">False</span>).to_string())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bộ feature cuối (13): ['nhiet_do_moi_truong', 'nhiet_do_quy_trinh', 'toc_do_quay', 'momen_xoan', 'do_mon_dao', 'chenh_lech_nhiet', 'cong_suat_co', 'tich_mon_momen', 'strain_index', 'loai_san_pham_L', 'loai_san_pham_M', 'ca_lam_viec_Sáng', 'ca_lam_viec_Đêm']

|mean| train sau scale (≈0): 0.0000
mean test sau scale (lệch khỏi 0 = shift):
nhiet_do_moi_truong    1.262
nhiet_do_quy_trinh     0.858
chenh_lech_nhiet      -0.601
toc_do_quay            0.401
momen_xoan            -0.339
strain_index          -0.192
cong_suat_co          -0.155
tich_mon_momen        -0.131
do_mon_dao            -0.005</code></pre>
</div>
</div>
<p><strong>Nhận xét 2.3 (chống rò rỉ dữ liệu).</strong> Scaler chỉ “nhìn” thống kê của Train (mean/std của Dây chuyền A). Sau transform: <strong>train có mean ≈ 0</strong>, còn <strong>test lệch hẳn</strong> (nhiệt độ môi trường test ở mức <strong>+1.26 độ lệch chuẩn</strong>). Con số này vừa xác nhận <strong>không rò rỉ Test</strong>, vừa cho thấy <strong>shift là thật</strong> và sẽ được xử lý ở Phần 3.</p>
<p><strong>Xử lý imbalance:</strong> dùng <code>class_weight='balanced'</code> cho mọi mô hình (phạt nặng lỗi ở lớp thiểu số). Đây là cách ổn định hơn SMOTE khi có shift (SMOTE nội suy mẫu train, dễ khuếch đại vùng không khớp với test). Ô dưới minh hoạ SMOTE để đối chiếu.</p>
<div id="5ce38fae" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T02:58:26.805973Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T02:58:26.805881Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T02:58:26.832839Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T02:58:26.832366Z&quot;}}" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># (Tuỳ chọn) Minh hoạ SMOTE — để đối chiếu; các mô hình chính dùng class_weight</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> imblearn.over_sampling <span class="im">import</span> SMOTE</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>Xsm, ysm <span class="op">=</span> SMOTE(random_state<span class="op">=</span>RANDOM_STATE).fit_resample(Xtr, ytr)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Trước SMOTE: </span><span class="sc">{</span>np<span class="sc">.</span>bincount(ytr)<span class="sc">}</span><span class="ss">  -&gt;  Sau SMOTE: </span><span class="sc">{</span>np<span class="sc">.</span>bincount(ysm)<span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Trước SMOTE: [12969  1031]  -&gt;  Sau SMOTE: [12969 12969]</code></pre>
</div>
</div>
<hr>
</section>
</section>
<section id="phần-3-phát-hiện-xử-lý-distribution-shift" class="level1">
<h1>Phần 3 — Phát hiện &amp; Xử lý Distribution Shift</h1>
<p>Ba nhiệm vụ: (1) <strong>PSI + KS-Test</strong> cho mọi feature số, phân loại mức shift; (2) <strong>Drift Classifier</strong> (AUC + feature importance) tìm feature “thủ phạm”; (3) áp dụng kỹ thuật xử lý shift (<strong>Importance Reweighting</strong> theo density-ratio + <strong>Threshold Calibration</strong>), so sánh hiệu năng trước/sau.</p>
<section id="psi-ks-test-cho-tất-cả-feature-số" class="level3">
<h3 class="anchored" data-anchor-id="psi-ks-test-cho-tất-cả-feature-số">3.1 PSI &amp; KS-Test cho tất cả feature số</h3>
<div id="972b4232" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T02:58:26.834070Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T02:58:26.834002Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T02:58:26.868500Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T02:58:26.868059Z&quot;}}" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> psi(expected, actual, bins<span class="op">=</span><span class="dv">10</span>):</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Population Stability Index — chia bin theo phân vị của tập expected (train)."""</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    qs <span class="op">=</span> np.quantile(expected, np.linspace(<span class="dv">0</span>,<span class="dv">1</span>,bins<span class="op">+</span><span class="dv">1</span>))<span class="op">;</span> qs[<span class="dv">0</span>], qs[<span class="op">-</span><span class="dv">1</span>] <span class="op">=</span> <span class="op">-</span>np.inf, np.inf</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    qs <span class="op">=</span> np.unique(qs)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    e <span class="op">=</span> np.clip(np.histogram(expected, bins<span class="op">=</span>qs)[<span class="dv">0</span>]<span class="op">/</span><span class="bu">len</span>(expected), <span class="fl">1e-6</span>, <span class="va">None</span>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    a <span class="op">=</span> np.clip(np.histogram(actual,   bins<span class="op">=</span>qs)[<span class="dv">0</span>]<span class="op">/</span><span class="bu">len</span>(actual),   <span class="fl">1e-6</span>, <span class="va">None</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">float</span>(np.<span class="bu">sum</span>((a<span class="op">-</span>e)<span class="op">*</span>np.log(a<span class="op">/</span>e)))</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> shift_level(p):  <span class="co"># ngưỡng PSI chuẩn ngành</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="st">'Không'</span> <span class="cf">if</span> p<span class="op">&lt;</span><span class="fl">0.1</span> <span class="cf">else</span> (<span class="st">'Nhẹ'</span> <span class="cf">if</span> p<span class="op">&lt;</span><span class="fl">0.25</span> <span class="cf">else</span> <span class="st">'Mạnh'</span>)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>rows<span class="op">=</span>[]</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> ALL_NUM:</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>    p <span class="op">=</span> psi(train_fe[col].values, test_fe[col].values)</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>    ks, pval <span class="op">=</span> ks_2samp(train_fe[col].values, test_fe[col].values)</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>    rows.append({<span class="st">'feature'</span>:col,<span class="st">'PSI'</span>:<span class="bu">round</span>(p,<span class="dv">4</span>),<span class="st">'muc_shift'</span>:shift_level(p),</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>                 <span class="st">'KS_stat'</span>:<span class="bu">round</span>(ks,<span class="dv">4</span>),<span class="st">'KS_pvalue'</span>:<span class="ss">f'</span><span class="sc">{</span>pval<span class="sc">:.2e}</span><span class="ss">'</span>})</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>shift_df <span class="op">=</span> pd.DataFrame(rows).sort_values(<span class="st">'PSI'</span>, ascending<span class="op">=</span><span class="va">False</span>).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>display(shift_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">feature</th>
<th data-quarto-table-cell-role="th">PSI</th>
<th data-quarto-table-cell-role="th">muc_shift</th>
<th data-quarto-table-cell-role="th">KS_stat</th>
<th data-quarto-table-cell-role="th">KS_pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>nhiet_do_moi_truong</td>
<td>1.0815</td>
<td>Mạnh</td>
<td>0.4277</td>
<td>0.00e+00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>nhiet_do_quy_trinh</td>
<td>0.5513</td>
<td>Mạnh</td>
<td>0.3070</td>
<td>0.00e+00</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>chenh_lech_nhiet</td>
<td>0.3194</td>
<td>Mạnh</td>
<td>0.2270</td>
<td>1.23e-190</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>toc_do_quay</td>
<td>0.1557</td>
<td>Nhẹ</td>
<td>0.1676</td>
<td>1.38e-103</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>momen_xoan</td>
<td>0.1195</td>
<td>Nhẹ</td>
<td>0.1386</td>
<td>7.30e-71</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>strain_index</td>
<td>0.0478</td>
<td>Không</td>
<td>0.0818</td>
<td>6.49e-25</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>cong_suat_co</td>
<td>0.0231</td>
<td>Không</td>
<td>0.0608</td>
<td>6.37e-14</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>tich_mon_momen</td>
<td>0.0194</td>
<td>Không</td>
<td>0.0567</td>
<td>3.41e-12</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>do_mon_dao</td>
<td>0.0013</td>
<td>Không</td>
<td>0.0092</td>
<td>8.65e-01</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="66bcf524" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T02:58:26.869645Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T02:58:26.869581Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T02:58:26.939094Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T02:58:26.938728Z&quot;}}" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="fl">4.2</span>))<span class="op">;</span> sd <span class="op">=</span> shift_df.sort_values(<span class="st">'PSI'</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>cmap <span class="op">=</span> {<span class="st">'Không'</span>:C_A,<span class="st">'Nhẹ'</span>:<span class="st">'#DD8452'</span>,<span class="st">'Mạnh'</span>:C_B}</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>bars <span class="op">=</span> ax.barh(sd[<span class="st">'feature'</span>], sd[<span class="st">'PSI'</span>], color<span class="op">=</span>[cmap[m] <span class="cf">for</span> m <span class="kw">in</span> sd[<span class="st">'muc_shift'</span>]])</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>ax.axvline(<span class="fl">0.1</span>, color<span class="op">=</span>C_GREY, ls<span class="op">=</span><span class="st">'--'</span>, lw<span class="op">=</span><span class="dv">1</span>)<span class="op">;</span> ax.axvline(<span class="fl">0.25</span>, color<span class="op">=</span>C_B, ls<span class="op">=</span><span class="st">'--'</span>, lw<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> b,v <span class="kw">in</span> <span class="bu">zip</span>(bars, sd[<span class="st">'PSI'</span>]): ax.text(v, b.get_y()<span class="op">+</span>b.get_height()<span class="op">/</span><span class="dv">2</span>, <span class="ss">f' </span><span class="sc">{</span>v<span class="sc">:.2f}</span><span class="ss">'</span>, va<span class="op">=</span><span class="st">'center'</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'PSI (Population Stability Index)'</span>)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Shift mạnh nhất ở nhóm nhiệt độ; độ mòn dao &amp; feature "strain" ổn định'</span>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>ax.legend(handles<span class="op">=</span>[Patch(color<span class="op">=</span>C_B,label<span class="op">=</span><span class="st">'Mạnh (PSI≥0.25)'</span>),Patch(color<span class="op">=</span><span class="st">'#DD8452'</span>,label<span class="op">=</span><span class="st">'Nhẹ (0.1–0.25)'</span>),</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>                   Patch(color<span class="op">=</span>C_A,label<span class="op">=</span><span class="st">'Không (&lt;0.1)'</span>)], frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">8</span>, loc<span class="op">=</span><span class="st">'lower right'</span>)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="CNC_Failure_Distribution_Shift_files/figure-html/cell-16-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Nhận xét 3.1.</strong> Bảng PSI/KS phân loại rõ mức shift (KS p-value ≈ 0 ở hầu hết feature vì n lớn, nên <strong>PSI là thước đo độ lớn đáng tin hơn</strong>): - <strong>Shift MẠNH (PSI ≥ 0.25):</strong> <code>nhiet_do_moi_truong</code> (1.08), <code>nhiet_do_quy_trinh</code> (0.55), <code>chenh_lech_nhiet</code> (0.32) — đúng bối cảnh nhà máy B nóng hơn. - <strong>Shift NHẸ:</strong> <code>toc_do_quay</code> (0.16), <code>momen_xoan</code> (0.12). - <strong>KHÔNG shift:</strong> <code>do_mon_dao</code> và các feature cơ học <code>strain_index</code>, <code>cong_suat_co</code>, <code>tich_mon_momen</code>.</p>
<blockquote class="blockquote">
<p><strong>Insight quan trọng:</strong> các feature cơ học ta tự tạo <strong>ổn định</strong> giữa hai dây chuyền — chúng vừa dự báo tốt (Phần 2) vừa <strong>kháng shift</strong>, nên là nền tảng vững để mô hình tổng quát hoá sang Dây chuyền B.</p>
</blockquote>
</section>
<section id="drift-classifier-tìm-feature-thủ-phạm-gây-shift" class="level3">
<h3 class="anchored" data-anchor-id="drift-classifier-tìm-feature-thủ-phạm-gây-shift">3.2 Drift Classifier — tìm feature ‘thủ phạm’ gây shift</h3>
<div id="db5d6267" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T02:58:26.940321Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T02:58:26.940261Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T02:58:46.216239Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T02:58:46.215757Z&quot;}}" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gán train=0, test=1; nếu phân biệt được tốt (AUC≫0.5) =&gt; có shift. Feature importance = thủ phạm.</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>Xdrift <span class="op">=</span> pd.concat([train_fe[ALL_NUM], test_fe[ALL_NUM]], axis<span class="op">=</span><span class="dv">0</span>).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>ydrift <span class="op">=</span> np.r_[np.zeros(<span class="bu">len</span>(train_fe)), np.ones(<span class="bu">len</span>(test_fe))]</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>cv_drift <span class="op">=</span> StratifiedKFold(<span class="dv">5</span>, shuffle<span class="op">=</span><span class="va">True</span>, random_state<span class="op">=</span>RANDOM_STATE)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>rf_drift <span class="op">=</span> RandomForestClassifier(n_estimators<span class="op">=</span><span class="dv">300</span>, max_depth<span class="op">=</span><span class="dv">8</span>, min_samples_leaf<span class="op">=</span><span class="dv">20</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>                                  random_state<span class="op">=</span>RANDOM_STATE, n_jobs<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="co"># RF thô cho xác suất bị "nén" lệch về 0/1 (không hiệu chỉnh tốt). Bọc CalibratedClassifierCV để có</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="co"># xác suất CHUẨN — cross_val_predict (OOF) tránh AUC lạc quan giả do đánh giá trong mẫu, và chính</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="co"># proba_drift này được TÁI DÙNG ở mục 3.3 cho Importance Reweighting (không cần huấn luyện thêm</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="co"># một LogisticRegression riêng — vì RF bất biến với scaling, dùng thẳng feature thô cũng hợp lệ).</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>drift_clf <span class="op">=</span> CalibratedClassifierCV(rf_drift, cv<span class="op">=</span>cv_drift)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>proba_drift <span class="op">=</span> cross_val_predict(drift_clf, Xdrift, ydrift, cv<span class="op">=</span>cv_drift,</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>                                method<span class="op">=</span><span class="st">'predict_proba'</span>, n_jobs<span class="op">=</span><span class="dv">3</span>)[:,<span class="dv">1</span>]</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>drift_auc <span class="op">=</span> roc_auc_score(ydrift, proba_drift)</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>rf_drift.fit(Xdrift, ydrift)   <span class="co"># fit trên toàn bộ — chỉ dùng để đọc Gini importance &amp; giải thích SHAP</span></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>imp <span class="op">=</span> pd.Series(rf_drift.feature_importances_, index<span class="op">=</span>ALL_NUM).sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Drift Classifier AUC (5-fold CV, xác suất đã hiệu chỉnh) = </span><span class="sc">{</span>drift_auc<span class="sc">:.4f}</span><span class="ss">   (0.5 = không phân biệt được; 1.0 = tách hoàn toàn)'</span>)</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">11.5</span>, <span class="dv">4</span>))</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> axes[<span class="dv">0</span>]<span class="op">;</span> imps <span class="op">=</span> imp.sort_values()</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>bars <span class="op">=</span> ax.barh(imps.index, imps.values, color<span class="op">=</span>[C_B <span class="cf">if</span> v<span class="op">&gt;</span><span class="fl">0.1</span> <span class="cf">else</span> C_GREY <span class="cf">for</span> v <span class="kw">in</span> imps])</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> b,v <span class="kw">in</span> <span class="bu">zip</span>(bars, imps.values): ax.text(v, b.get_y()<span class="op">+</span>b.get_height()<span class="op">/</span><span class="dv">2</span>, <span class="ss">f' </span><span class="sc">{</span>v<span class="sc">:.2f}</span><span class="ss">'</span>, va<span class="op">=</span><span class="st">'center'</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Độ quan trọng (Gini, Random Forest)'</span>)<span class="op">;</span> ax.margins(x<span class="op">=</span><span class="fl">0.12</span>)</span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Feature importance: mức độ, không cho biết chiều tác động'</span>)</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> axes[<span class="dv">1</span>]</span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a>fpr, tpr, _ <span class="op">=</span> roc_curve(ydrift, proba_drift)</span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a>ax.plot(fpr, tpr, color<span class="op">=</span>C_B, lw<span class="op">=</span><span class="fl">1.8</span>, label<span class="op">=</span><span class="ss">f'Drift classifier (AUC=</span><span class="sc">{</span>drift_auc<span class="sc">:.2f}</span><span class="ss">)'</span>)</span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a>ax.plot([<span class="dv">0</span>,<span class="dv">1</span>], [<span class="dv">0</span>,<span class="dv">1</span>], <span class="st">'k:'</span>, lw<span class="op">=</span><span class="fl">0.8</span>, label<span class="op">=</span><span class="st">'Ngẫu nhiên (AUC=0.50)'</span>)</span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a>ax.fill_between(fpr, tpr, fpr, color<span class="op">=</span>C_B, alpha<span class="op">=</span><span class="fl">0.08</span>)</span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'False Positive Rate'</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">'True Positive Rate'</span>)</span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'ROC: hai dây chuyền tách nhau rõ khỏi đường chéo ngẫu nhiên'</span>)</span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="ss">f'Drift Classifier (AUC=</span><span class="sc">{</span>drift_auc<span class="sc">:.2f}</span><span class="ss">): nhiệt độ môi trường là "thủ phạm" chính'</span>, y<span class="op">=</span><span class="fl">1.03</span>)</span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()<span class="op">;</span> plt.show()</span>
<span id="cb25-37"><a href="#cb25-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-38"><a href="#cb25-38" aria-hidden="true" tabindex="-1"></a><span class="co"># SHAP summary plot: bổ sung CHIỀU tác động mà Gini importance "mù" — điểm màu đỏ (giá trị feature cao)</span></span>
<span id="cb25-39"><a href="#cb25-39" aria-hidden="true" tabindex="-1"></a><span class="co"># nằm bên phải (SHAP dương) nghĩa là giá trị cao của feature đó đẩy dự đoán nghiêng về nhãn 1 (Dây chuyền B).</span></span>
<span id="cb25-40"><a href="#cb25-40" aria-hidden="true" tabindex="-1"></a>fe_labels_full <span class="op">=</span> {<span class="st">'nhiet_do_moi_truong'</span>:<span class="st">'Nhiệt độ môi trường'</span>,<span class="st">'nhiet_do_quy_trinh'</span>:<span class="st">'Nhiệt độ quy trình'</span>,</span>
<span id="cb25-41"><a href="#cb25-41" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'toc_do_quay'</span>:<span class="st">'Tốc độ quay'</span>,<span class="st">'momen_xoan'</span>:<span class="st">'Mômen xoắn'</span>,<span class="st">'do_mon_dao'</span>:<span class="st">'Độ mòn dao'</span>,</span>
<span id="cb25-42"><a href="#cb25-42" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'chenh_lech_nhiet'</span>:<span class="st">'Chênh lệch nhiệt'</span>,<span class="st">'cong_suat_co'</span>:<span class="st">'Công suất cơ'</span>,</span>
<span id="cb25-43"><a href="#cb25-43" aria-hidden="true" tabindex="-1"></a>                  <span class="st">'tich_mon_momen'</span>:<span class="st">'Mòn × Mômen'</span>,<span class="st">'strain_index'</span>:<span class="st">'Chỉ số quá tải'</span>}</span>
<span id="cb25-44"><a href="#cb25-44" aria-hidden="true" tabindex="-1"></a>shap_sample <span class="op">=</span> Xdrift.sample(n<span class="op">=</span><span class="bu">min</span>(<span class="dv">2000</span>, <span class="bu">len</span>(Xdrift)), random_state<span class="op">=</span>RANDOM_STATE)</span>
<span id="cb25-45"><a href="#cb25-45" aria-hidden="true" tabindex="-1"></a>explainer <span class="op">=</span> shap.TreeExplainer(rf_drift)</span>
<span id="cb25-46"><a href="#cb25-46" aria-hidden="true" tabindex="-1"></a>shap_values <span class="op">=</span> explainer.shap_values(shap_sample)</span>
<span id="cb25-47"><a href="#cb25-47" aria-hidden="true" tabindex="-1"></a>sv_pos <span class="op">=</span> shap_values[:, :, <span class="dv">1</span>] <span class="cf">if</span> <span class="bu">getattr</span>(shap_values, <span class="st">'ndim'</span>, <span class="dv">0</span>) <span class="op">==</span> <span class="dv">3</span> <span class="cf">else</span> shap_values[<span class="dv">1</span>]</span>
<span id="cb25-48"><a href="#cb25-48" aria-hidden="true" tabindex="-1"></a>shap.summary_plot(sv_pos, shap_sample.rename(columns<span class="op">=</span>fe_labels_full), show<span class="op">=</span><span class="va">False</span>, plot_size<span class="op">=</span>(<span class="fl">7.5</span>, <span class="dv">4</span>))</span>
<span id="cb25-49"><a href="#cb25-49" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'SHAP — chiều tác động lên xác suất "là Dây chuyền B"'</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb25-50"><a href="#cb25-50" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Drift Classifier AUC (5-fold CV, xác suất đã hiệu chỉnh) = 0.8283   (0.5 = không phân biệt được; 1.0 = tách hoàn toàn)</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="CNC_Failure_Distribution_Shift_files/figure-html/cell-17-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="CNC_Failure_Distribution_Shift_files/figure-html/cell-17-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Nhận xét 3.2.</strong> Drift classifier đạt <strong>AUC ≈ 0.83</strong> (xác suất đã hiệu chỉnh bằng <code>CalibratedClassifierCV</code>) — hai dây chuyền <strong>rất dễ phân biệt</strong> → khẳng định covariate shift là thật (không phải nhiễu ngẫu nhiên). Đường ROC nằm hẳn phía trên đường chéo ngẫu nhiên, trực quan hoá đúng mức độ tách biệt đó.</p>
<p>“Thủ phạm” xếp hạng theo Gini importance: <code>nhiet_do_moi_truong</code> (0.46) ≫ <code>nhiet_do_quy_trinh</code> (0.19) ≈ <code>chenh_lech_nhiet</code> (0.18). Kết quả <strong>nhất quán với PSI</strong> ở mục 3.1. SHAP summary plot bổ sung thêm <strong>chiều</strong> tác động mà Gini importance không thể hiện: các điểm <strong>nhiệt độ môi trường cao (đỏ)</strong> nằm ở phía SHAP dương — tức đẩy xác suất dự đoán nghiêng hẳn về nhãn 1 (Dây chuyền B), đúng bối cảnh “Dây chuyền B nóng hơn”.</p>
</section>
<section id="xử-lý-shift-importance-reweighting-threshold-calibration" class="level3">
<h3 class="anchored" data-anchor-id="xử-lý-shift-importance-reweighting-threshold-calibration">3.3 Xử lý shift: Importance Reweighting + Threshold Calibration</h3>
<div id="e2207af8" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T02:58:46.217511Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T02:58:46.217425Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T02:58:46.220329Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T02:58:46.219963Z&quot;}}" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># (a) IMPORTANCE REWEIGHTING theo density-ratio: w(x) = p_test(x)/p_train(x)</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co">#     Tái dùng chính proba_drift (xác suất OOF, đã hiệu chỉnh) từ Drift Classifier ở mục 3.2 thay vì</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co">#     huấn luyện thêm một LogisticRegression riêng: Xdrift được ghép [train_fe, test_fe] theo đúng thứ</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co">#     tự đó, nên 14000 dòng ĐẦU của proba_drift chính là s(x) = P(là Test | x) OOF cho từng mẫu Train.</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>s <span class="op">=</span> proba_drift[:<span class="bu">len</span>(train_fe)]</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>w <span class="op">=</span> (s<span class="op">/</span>(<span class="dv">1</span><span class="op">-</span>s)) <span class="op">*</span> ((ydrift<span class="op">==</span><span class="dv">0</span>).<span class="bu">sum</span>()<span class="op">/</span>(ydrift<span class="op">==</span><span class="dv">1</span>).<span class="bu">sum</span>())</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>w <span class="op">=</span> np.clip(w, np.quantile(w,<span class="fl">0.01</span>), np.quantile(w,<span class="fl">0.99</span>))<span class="op">;</span> w <span class="op">=</span> w<span class="op">/</span>w.mean()   <span class="co"># cắt đuôi + chuẩn hoá</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>ess <span class="op">=</span> (w.<span class="bu">sum</span>()<span class="op">**</span><span class="dv">2</span>)<span class="op">/</span>(w<span class="op">**</span><span class="dv">2</span>).<span class="bu">sum</span>()</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Trọng số density-ratio: min=</span><span class="sc">{</span>w<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.3f}</span><span class="ss">, median=</span><span class="sc">{</span>np<span class="sc">.</span>median(w)<span class="sc">:.3f}</span><span class="ss">, max=</span><span class="sc">{</span>w<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.3f}</span><span class="ss">'</span>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Effective sample size = </span><span class="sc">{</span>ess<span class="sc">:.0f}</span><span class="ss">/</span><span class="sc">{</span><span class="bu">len</span>(w)<span class="sc">}</span><span class="ss"> (</span><span class="sc">{</span>ess<span class="op">/</span><span class="bu">len</span>(w)<span class="op">*</span><span class="dv">100</span><span class="sc">:.0f}</span><span class="ss">%)'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Trọng số density-ratio: min=0.215, median=0.398, max=13.993
Effective sample size = 2821/14000 (20%)</code></pre>
</div>
</div>
<div id="d56953c1" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T02:58:46.221334Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T02:58:46.221265Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T02:58:54.084352Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T02:58:54.083931Z&quot;}}" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># (b) So sánh hiệu năng TRƯỚC/SAU xử lý trên Test (Dây chuyền B). Mô hình đại diện: HistGBM.</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> eval_at(y, p, thr):</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>    pred<span class="op">=</span>(p<span class="op">&gt;=</span>thr).astype(<span class="bu">int</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">dict</span>(AUC_ROC<span class="op">=</span>roc_auc_score(y,p), AUC_PR<span class="op">=</span>average_precision_score(y,p), F1<span class="op">=</span>f1_score(y,pred), threshold<span class="op">=</span>thr)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>mk <span class="op">=</span> <span class="kw">lambda</span>: HistGradientBoostingClassifier(random_state<span class="op">=</span>RANDOM_STATE, class_weight<span class="op">=</span><span class="st">'balanced'</span>,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>                                            max_iter<span class="op">=</span><span class="dv">200</span>, learning_rate<span class="op">=</span><span class="fl">0.08</span>, max_depth<span class="op">=</span><span class="dv">4</span>)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>cv <span class="op">=</span> StratifiedKFold(<span class="dv">5</span>, shuffle<span class="op">=</span><span class="va">True</span>, random_state<span class="op">=</span>RANDOM_STATE)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>m_base <span class="op">=</span> mk().fit(Xtr, ytr)<span class="op">;</span>              p_base <span class="op">=</span> m_base.predict_proba(Xte)[:,<span class="dv">1</span>]   <span class="co"># baseline</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>m_rw   <span class="op">=</span> mk().fit(Xtr, ytr, sample_weight<span class="op">=</span>w)<span class="op">;</span> p_rw <span class="op">=</span> m_rw.predict_proba(Xte)[:,<span class="dv">1</span>]   <span class="co"># reweighted</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="co"># THRESHOLD CALIBRATION — QUY TRÌNH CHUẨN DÙNG CHUNG TOÀN BÀI (giống Phần 4):</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="co">#   ngưỡng F1-tối ưu chọn trên OOF của TRAIN, KHÔNG trọng số, trung bình qua 5 seed OOF</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a><span class="co">#   (argmax trên một seed đơn lẻ dao động mạnh ~0.6–0.8 → trung bình hoá để giảm phương sai).</span></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a><span class="co">#   Test không tham gia bất kỳ bước chọn ngưỡng nào.</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a><span class="co">#   (Biến thể "nhạy shift" — đánh trọng số OOF theo density-ratio w — đã thử, cho ngưỡng tương đương;</span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a><span class="co">#    chọn bản không trọng số để TOÀN pipeline dùng một quy trình ngưỡng duy nhất.)</span></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>THR_SEEDS <span class="op">=</span> (<span class="dv">42</span>, <span class="dv">1</span>, <span class="dv">7</span>, <span class="dv">13</span>, <span class="dv">99</span>)</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> f1_optimal_thr(make_model, seeds<span class="op">=</span>THR_SEEDS):</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>    thrs <span class="op">=</span> []</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> s <span class="kw">in</span> seeds:</span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>        oof <span class="op">=</span> cross_val_predict(make_model(), Xtr, ytr,</span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>                                cv<span class="op">=</span>StratifiedKFold(<span class="dv">5</span>, shuffle<span class="op">=</span><span class="va">True</span>, random_state<span class="op">=</span>s),</span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a>                                method<span class="op">=</span><span class="st">'predict_proba'</span>, n_jobs<span class="op">=-</span><span class="dv">1</span>)[:,<span class="dv">1</span>]</span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a>        pr, rc, th <span class="op">=</span> precision_recall_curve(ytr, oof)</span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a>        f1s <span class="op">=</span> <span class="dv">2</span><span class="op">*</span>pr<span class="op">*</span>rc<span class="op">/</span>(pr<span class="op">+</span>rc<span class="op">+</span><span class="fl">1e-9</span>)</span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a>        thrs.append(th[np.argmax(f1s[:<span class="op">-</span><span class="dv">1</span>])])</span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">float</span>(np.mean(thrs))</span>
<span id="cb29-29"><a href="#cb29-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-30"><a href="#cb29-30" aria-hidden="true" tabindex="-1"></a>thr_star <span class="op">=</span> f1_optimal_thr(mk)</span>
<span id="cb29-31"><a href="#cb29-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Ngưỡng F1-tối ưu (OOF train không trọng số, trung bình 5 seed) = </span><span class="sc">{</span>thr_star<span class="sc">:.3f}</span><span class="ch">\n</span><span class="ss">'</span>)</span>
<span id="cb29-32"><a href="#cb29-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-33"><a href="#cb29-33" aria-hidden="true" tabindex="-1"></a>shift_cmp <span class="op">=</span> pd.DataFrame({</span>
<span id="cb29-34"><a href="#cb29-34" aria-hidden="true" tabindex="-1"></a>  <span class="st">'Baseline (thr=0.5)'</span>:          eval_at(yte, p_base, <span class="fl">0.5</span>),</span>
<span id="cb29-35"><a href="#cb29-35" aria-hidden="true" tabindex="-1"></a>  <span class="st">'Threshold Calibration'</span>:       eval_at(yte, p_base, thr_star),</span>
<span id="cb29-36"><a href="#cb29-36" aria-hidden="true" tabindex="-1"></a>  <span class="st">'Importance Reweighting'</span>:      eval_at(yte, p_rw, <span class="fl">0.5</span>),</span>
<span id="cb29-37"><a href="#cb29-37" aria-hidden="true" tabindex="-1"></a>  <span class="st">'Reweight + Threshold Calib.'</span>: eval_at(yte, p_rw, thr_star),</span>
<span id="cb29-38"><a href="#cb29-38" aria-hidden="true" tabindex="-1"></a>}).T[[<span class="st">'AUC_ROC'</span>,<span class="st">'AUC_PR'</span>,<span class="st">'F1'</span>,<span class="st">'threshold'</span>]].<span class="bu">round</span>(<span class="dv">4</span>)</span>
<span id="cb29-39"><a href="#cb29-39" aria-hidden="true" tabindex="-1"></a>display(shift_cmp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Ngưỡng F1-tối ưu (OOF train không trọng số, trung bình 5 seed) = 0.762
</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">AUC_ROC</th>
<th data-quarto-table-cell-role="th">AUC_PR</th>
<th data-quarto-table-cell-role="th">F1</th>
<th data-quarto-table-cell-role="th">threshold</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">Baseline (thr=0.5)</th>
<td>0.8740</td>
<td>0.6696</td>
<td>0.7571</td>
<td>0.5000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Threshold Calibration</th>
<td>0.8740</td>
<td>0.6696</td>
<td>0.7706</td>
<td>0.7624</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Importance Reweighting</th>
<td>0.8651</td>
<td>0.6578</td>
<td>0.7578</td>
<td>0.5000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Reweight + Threshold Calib.</th>
<td>0.8651</td>
<td>0.6578</td>
<td>0.7735</td>
<td>0.7624</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="6eefd18e" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T02:58:54.085568Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T02:58:54.085470Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T02:58:54.190506Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T02:58:54.190177Z&quot;}}" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">3.8</span>))</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>ax<span class="op">=</span>axes[<span class="dv">0</span>]<span class="op">;</span> names<span class="op">=</span><span class="bu">list</span>(shift_cmp.index)<span class="op">;</span> f1v<span class="op">=</span>shift_cmp[<span class="st">'F1'</span>].values</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>cols<span class="op">=</span>[C_GREY,<span class="st">'#55A868'</span>,C_A,C_B]</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>bars<span class="op">=</span>ax.barh(<span class="bu">range</span>(<span class="bu">len</span>(names)), f1v, color<span class="op">=</span>cols)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>ax.set_yticks(<span class="bu">range</span>(<span class="bu">len</span>(names)))<span class="op">;</span> ax.set_yticklabels(names, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i,v <span class="kw">in</span> <span class="bu">enumerate</span>(f1v): ax.text(v, i, <span class="ss">f' </span><span class="sc">{</span>v<span class="sc">:.3f}</span><span class="ss">'</span>, va<span class="op">=</span><span class="st">'center'</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>ax.axvline(shift_cmp.loc[<span class="st">'Baseline (thr=0.5)'</span>,<span class="st">'F1'</span>], color<span class="op">=</span>C_GREY, ls<span class="op">=</span><span class="st">'--'</span>, lw<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'F1 trên Dây chuyền B (Test)'</span>)<span class="op">;</span> ax.set_xlim(<span class="fl">0.72</span>,<span class="fl">0.80</span>)</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Threshold Calibration cải thiện F1 rõ nhất'</span>)<span class="op">;</span> ax.invert_yaxis()</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>ax<span class="op">=</span>axes[<span class="dv">1</span>]</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> p,lab,c <span class="kw">in</span> [(p_base,<span class="st">'Baseline'</span>,C_GREY),(p_rw,<span class="st">'Reweighted'</span>,C_B)]:</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>    pr,rc,_<span class="op">=</span>precision_recall_curve(yte,p)</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>    ax.plot(rc,pr,color<span class="op">=</span>c,lw<span class="op">=</span><span class="fl">1.8</span>,label<span class="op">=</span><span class="ss">f'</span><span class="sc">{</span>lab<span class="sc">}</span><span class="ss"> (AP=</span><span class="sc">{</span>average_precision_score(yte,p)<span class="sc">:.3f}</span><span class="ss">)'</span>)</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>ax.axhline(yte.mean(),color<span class="op">=</span><span class="st">'k'</span>,ls<span class="op">=</span><span class="st">':'</span>,lw<span class="op">=</span><span class="fl">0.8</span>,label<span class="op">=</span><span class="ss">f'Ngẫu nhiên (</span><span class="sc">{</span>yte<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">)'</span>)</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Recall'</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">'Precision'</span>)<span class="op">;</span> ax.set_title(<span class="st">'Precision-Recall trên Test'</span>)</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>,fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">'Xử lý shift: hiệu chỉnh ngưỡng có lợi; reweighting không cải thiện AUC'</span>, y<span class="op">=</span><span class="fl">1.03</span>)</span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="CNC_Failure_Distribution_Shift_files/figure-html/cell-20-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Nhận xét 3.3 (kết quả trung thực &amp; cách diễn giải).</strong> - <strong>Threshold Calibration cải thiện F1: 0.757 → 0.771</strong> (+0.014). Vì lớp hỏng hiếm, ngưỡng 0.5 mặc định không tối ưu. Ngưỡng F1-tối ưu được chọn trên <strong>OOF của train — không trọng số, trung bình qua 5 seed</strong> (cùng MỘT quy trình chuẩn với Phần 4). Trung bình 5 seed vì argmax trên một seed đơn lẻ dao động mạnh (~0.6–0.8) trong khi đường F1 quanh đỉnh khá phẳng → mục đích là <strong>giảm phương sai của ngưỡng</strong> (bảo hiểm), không phải tăng F1 kỳ vọng. Thao tác <strong>rẻ, an toàn, không đụng test — luôn nên làm</strong>. - <strong>Importance Reweighting KHÔNG cải thiện chất lượng xếp hạng</strong> (AUC-PR 0.670 → 0.658; AUC-ROC 0.874 → 0.865). Trọng số ở đây tái dùng xác suất OOF <strong>đã hiệu chỉnh</strong> của Drift Classifier (mục 3.2) — “quyết đoán” hơn bản LogisticRegression nên trọng số lệch mạnh hơn, <strong>ESS giảm còn ~20%</strong> (2,821/14,000 mẫu hiệu dụng). Điều này <strong>hợp lý về lý thuyết</strong>: đây là <strong>covariate shift thuần</strong> — P(y|x) ổn định (cùng cơ chế vật lý gây hỏng), nên đánh trọng số lại không sửa được thiên lệch nào mà chỉ tăng phương sai. Ở ngưỡng đã hiệu chỉnh, F1 của bản reweight (0.774) chỉ chênh bản không reweight (0.771) <strong>+0.003 — nằm trong nhiễu lấy mẫu</strong> và không bù được việc AUC-PR giảm. Reweighting chỉ hữu ích khi vùng đặc trưng test <strong>thiếu</strong> trong train; ở đây train đã phủ đủ. - <strong>Kết luận xử lý shift:</strong> với bài toán này, <strong>feature kháng-shift (Phần 2) + hiệu chỉnh ngưỡng</strong> là chiến lược hiệu quả nhất; reweighting được thử nghiệm đầy đủ nhưng <strong>không nên áp dụng</strong>. Giá trị thật của pipeline shift là <strong>giám sát khi triển khai</strong>: tính PSI định kỳ trên Dây chuyền B — nếu shift tiến hoá thành concept drift (P(y|x) đổi), hệ thống cảnh báo, gán nhãn dữ liệu B và huấn luyện lại.</p>
<hr>
</section>
</section>
<section id="phần-4-xây-dựng-mô-hình-đánh-giá" class="level1">
<h1>Phần 4 — Xây dựng mô hình &amp; Đánh giá</h1>
<p>Ba nhiệm vụ: (1) <strong>≥3 mô hình</strong> + tinh chỉnh siêu tham số bằng <strong>RandomizedSearchCV + Stratified K-Fold</strong>; (2) đánh giá đa chiều <strong>AUC-ROC, AUC-PR, F1, Precision-Recall curve</strong>; (3) bảng so sánh mô hình.</p>
<p>Ba mô hình: <strong>Logistic Regression</strong> (tuyến tính, dễ giải thích), <strong>Random Forest</strong>, <strong>HistGradientBoosting</strong> (phi tuyến, bắt tương tác cơ học). Tất cả dùng <code>class_weight='balanced'</code>. Scoring = <strong>average_precision (AUC-PR)</strong> — phù hợp dữ liệu mất cân bằng.</p>
<section id="hyperparameter-tuning-randomizedsearchcv-stratified-5-fold" class="level3">
<h3 class="anchored" data-anchor-id="hyperparameter-tuning-randomizedsearchcv-stratified-5-fold">4.1 Hyperparameter Tuning (RandomizedSearchCV + Stratified 5-Fold)</h3>
<div id="2dd0c446" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T02:58:54.191884Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T02:58:54.191803Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T03:01:37.353620Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T03:01:37.352874Z&quot;}}" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>cv <span class="op">=</span> StratifiedKFold(<span class="dv">5</span>, shuffle<span class="op">=</span><span class="va">True</span>, random_state<span class="op">=</span>RANDOM_STATE)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>searches <span class="op">=</span> {}</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>spaces <span class="op">=</span> {</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a> <span class="st">'Logistic Regression'</span>: (LogisticRegression(max_iter<span class="op">=</span><span class="dv">3000</span>, class_weight<span class="op">=</span><span class="st">'balanced'</span>, n_jobs<span class="op">=</span><span class="dv">3</span>),</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    {<span class="st">'C'</span>: loguniform(<span class="fl">1e-2</span>,<span class="fl">1e2</span>), <span class="st">'penalty'</span>:[<span class="st">'l1'</span>,<span class="st">'l2'</span>], <span class="st">'solver'</span>:[<span class="st">'liblinear'</span>]}),</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a> <span class="st">'Random Forest'</span>: (RandomForestClassifier(class_weight<span class="op">=</span><span class="st">'balanced'</span>, random_state<span class="op">=</span>RANDOM_STATE, n_jobs<span class="op">=</span><span class="dv">3</span>),</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>    {<span class="st">'n_estimators'</span>:randint(<span class="dv">200</span>,<span class="dv">500</span>),<span class="st">'max_depth'</span>:randint(<span class="dv">4</span>,<span class="dv">16</span>),</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>     <span class="st">'min_samples_leaf'</span>:randint(<span class="dv">5</span>,<span class="dv">50</span>),<span class="st">'max_features'</span>:[<span class="st">'sqrt'</span>,<span class="st">'log2'</span>,<span class="fl">0.5</span>]}),</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a> <span class="st">'HistGradientBoosting'</span>: (HistGradientBoostingClassifier(class_weight<span class="op">=</span><span class="st">'balanced'</span>, random_state<span class="op">=</span>RANDOM_STATE),</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>    {<span class="st">'learning_rate'</span>:loguniform(<span class="fl">0.02</span>,<span class="fl">0.3</span>),<span class="st">'max_iter'</span>:randint(<span class="dv">150</span>,<span class="dv">400</span>),<span class="st">'max_depth'</span>:randint(<span class="dv">3</span>,<span class="dv">8</span>),</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>     <span class="st">'l2_regularization'</span>:loguniform(<span class="fl">1e-3</span>,<span class="fl">1.0</span>),<span class="st">'min_samples_leaf'</span>:randint(<span class="dv">10</span>,<span class="dv">60</span>)}),</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="co"># n_iter=50: phủ không gian siêu tham số dày hơn (chỉ tốn compute, không đổi phương pháp).</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a><span class="co"># n_jobs=-1 ở search: song song hoá theo tổ hợp tham số — tính tái lập vẫn giữ nguyên vì</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a><span class="co"># danh sách tổ hợp được sinh từ random_state TRƯỚC khi chạy song song.</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name,(est,space) <span class="kw">in</span> spaces.items():</span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>    srch <span class="op">=</span> RandomizedSearchCV(est, space, n_iter<span class="op">=</span><span class="dv">50</span>, scoring<span class="op">=</span><span class="st">'average_precision'</span>,</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>                              cv<span class="op">=</span>cv, random_state<span class="op">=</span>RANDOM_STATE, n_jobs<span class="op">=</span><span class="dv">3</span>).fit(Xtr, ytr)</span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>    searches[name] <span class="op">=</span> srch</span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span>name<span class="sc">:22s}</span><span class="ss"> CV AUC-PR = </span><span class="sc">{</span>srch<span class="sc">.</span>best_score_<span class="sc">:.4f}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Logistic Regression    CV AUC-PR = 0.2731
Random Forest          CV AUC-PR = 0.6596
HistGradientBoosting   CV AUC-PR = 0.6584</code></pre>
</div>
</div>
</section>
<section id="đánh-giá-đa-chiều-trên-test-dây-chuyền-b-bảng-so-sánh" class="level3">
<h3 class="anchored" data-anchor-id="đánh-giá-đa-chiều-trên-test-dây-chuyền-b-bảng-so-sánh">4.2 Đánh giá đa chiều trên Test (Dây chuyền B) &amp; bảng so sánh</h3>
<div id="7f840c51" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T03:01:37.355237Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T03:01:37.355107Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T03:01:57.909644Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T03:01:57.909182Z&quot;}}" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> best_thr(model, seeds<span class="op">=</span>THR_SEEDS):</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Ngưỡng F1-tối ưu trên OOF train — CÙNG quy trình chuẩn với mục 3.3 (không trọng số, 5 seed).</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Trung bình qua 5 seed vì argmax trên một OOF đơn lẻ có phương sai lớn (thr* dao động ~0.6–0.8);</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># trung bình hoá làm thr* ổn định → F1 test đáng tin hơn. Tuyệt đối không đụng test.</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>    thrs <span class="op">=</span> []</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> s <span class="kw">in</span> seeds:</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>        oof <span class="op">=</span> cross_val_predict(model, Xtr, ytr,</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>                                cv<span class="op">=</span>StratifiedKFold(<span class="dv">5</span>, shuffle<span class="op">=</span><span class="va">True</span>, random_state<span class="op">=</span>s),</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>                                method<span class="op">=</span><span class="st">'predict_proba'</span>, n_jobs<span class="op">=-</span><span class="dv">1</span>)[:,<span class="dv">1</span>]</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>        pr, rc, th <span class="op">=</span> precision_recall_curve(ytr, oof)</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>        f1s <span class="op">=</span> <span class="dv">2</span><span class="op">*</span>pr<span class="op">*</span>rc<span class="op">/</span>(pr<span class="op">+</span>rc<span class="op">+</span><span class="fl">1e-9</span>)</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>        thrs.append(th[np.argmax(f1s[:<span class="op">-</span><span class="dv">1</span>])])</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">float</span>(np.mean(thrs))</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>rows, proba_store <span class="op">=</span> [], {}</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, srch <span class="kw">in</span> searches.items():</span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>    m <span class="op">=</span> srch.best_estimator_<span class="op">;</span> p <span class="op">=</span> m.predict_proba(Xte)[:,<span class="dv">1</span>]<span class="op">;</span> proba_store[name]<span class="op">=</span>p</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>    thr <span class="op">=</span> best_thr(m)<span class="op">;</span> pred<span class="op">=</span>(p<span class="op">&gt;=</span>thr).astype(<span class="bu">int</span>)</span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>    rows.append({<span class="st">'Model'</span>:name,<span class="st">'CV_AUC_PR'</span>:<span class="bu">round</span>(srch.best_score_,<span class="dv">4</span>),</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>                 <span class="st">'AUC_ROC'</span>:<span class="bu">round</span>(roc_auc_score(yte,p),<span class="dv">4</span>),<span class="st">'AUC_PR'</span>:<span class="bu">round</span>(average_precision_score(yte,p),<span class="dv">4</span>),</span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a>                 <span class="st">'F1@0.5'</span>:<span class="bu">round</span>(f1_score(yte,(p<span class="op">&gt;=</span><span class="fl">0.5</span>).astype(<span class="bu">int</span>)),<span class="dv">4</span>),</span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>                 <span class="st">'F1@thr*'</span>:<span class="bu">round</span>(f1_score(yte,pred),<span class="dv">4</span>),<span class="st">'thr*'</span>:<span class="bu">round</span>(thr,<span class="dv">3</span>)})</span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a>model_cmp <span class="op">=</span> pd.DataFrame(rows).sort_values(<span class="st">'F1@thr*'</span>, ascending<span class="op">=</span><span class="va">False</span>).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a>display(model_cmp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">CV_AUC_PR</th>
<th data-quarto-table-cell-role="th">AUC_ROC</th>
<th data-quarto-table-cell-role="th">AUC_PR</th>
<th data-quarto-table-cell-role="th">F1@0.5</th>
<th data-quarto-table-cell-role="th">F1@thr*</th>
<th data-quarto-table-cell-role="th">thr*</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Random Forest</td>
<td>0.6596</td>
<td>0.8790</td>
<td>0.6861</td>
<td>0.7645</td>
<td>0.7749</td>
<td>0.695</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>HistGradientBoosting</td>
<td>0.6584</td>
<td>0.8623</td>
<td>0.6606</td>
<td>0.7497</td>
<td>0.7689</td>
<td>0.754</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Logistic Regression</td>
<td>0.2731</td>
<td>0.7437</td>
<td>0.2378</td>
<td>0.2394</td>
<td>0.3075</td>
<td>0.678</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="b-chẩn-đoán-hội-tụ-n_iter-randomizedsearchcv" class="level3">
<h3 class="anchored" data-anchor-id="b-chẩn-đoán-hội-tụ-n_iter-randomizedsearchcv">4.2b Chẩn đoán hội tụ n_iter (RandomizedSearchCV)</h3>
<p>Kiểm tra <code>n_iter=50</code> (mục 4.1) đã đủ chưa: chạy <strong>1 lần</strong> với <code>n_iter</code> lớn cho mỗi mô hình, rồi lấy <em>best-score-so-far</em> (cummax) theo từng mốc <code>n_iter</code> — không cần chạy lại search nhiều lần vì <code>ParameterSampler</code> lấy mẫu tuần tự với <code>random_state</code> cố định, nên 50 mẫu đầu của lần chạy lớn trùng khớp với search chính <code>n_iter=50</code> ở mục 4.1.</p>
<div id="ea0cda82" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T03:01:57.910940Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T03:01:57.910840Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T03:06:39.420718Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T03:06:39.419773Z&quot;}}" data-execution_count="22">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Chẩn đoán: best CV AUC-PR hội tụ thế nào khi tăng n_iter? (chạy 1 lần n_iter lớn, lấy cummax)</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>N_ITER_MAX <span class="op">=</span> <span class="dv">60</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>conv_curves <span class="op">=</span> {}</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, (est, space) <span class="kw">in</span> spaces.items():</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    srch_diag <span class="op">=</span> RandomizedSearchCV(est, space, n_iter<span class="op">=</span>N_ITER_MAX, scoring<span class="op">=</span><span class="st">'average_precision'</span>,</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>                                    cv<span class="op">=</span>cv, random_state<span class="op">=</span>RANDOM_STATE, n_jobs<span class="op">=</span><span class="dv">3</span>).fit(Xtr, ytr)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>    scores <span class="op">=</span> srch_diag.cv_results_[<span class="st">'mean_test_score'</span>]  <span class="co"># đúng thứ tự sample tuần tự của ParameterSampler</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>    conv_curves[name] <span class="op">=</span> np.maximum.accumulate(scores)</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="fl">4.2</span>))</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> [C_A, C_B, C_GREY]</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (name, curve), c <span class="kw">in</span> <span class="bu">zip</span>(conv_curves.items(), colors):</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>    ax.plot(<span class="bu">range</span>(<span class="dv">1</span>, <span class="bu">len</span>(curve) <span class="op">+</span> <span class="dv">1</span>), curve, lw<span class="op">=</span><span class="fl">1.8</span>, label<span class="op">=</span>name, color<span class="op">=</span>c)</span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>ax.axvline(<span class="dv">50</span>, color<span class="op">=</span><span class="st">'k'</span>, ls<span class="op">=</span><span class="st">'--'</span>, lw<span class="op">=</span><span class="dv">1</span>, label<span class="op">=</span><span class="st">'n_iter=50 (đang dùng, mục 4.1)'</span>)</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'n_iter'</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">'Best CV AUC-PR (tính đến n_iter đó)'</span>)</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Hội tụ của RandomizedSearchCV theo n_iter'</span>)</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()<span class="op">;</span> plt.show()</span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'Model'</span><span class="sc">:22s}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'best@15'</span><span class="sc">:&gt;10s}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'best@50'</span><span class="sc">:&gt;10s}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'best@'</span> <span class="op">+</span> <span class="bu">str</span>(N_ITER_MAX)<span class="sc">:&gt;10s}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'gain 50→60'</span><span class="sc">:&gt;11s}</span><span class="ss">"</span>)</span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, curve <span class="kw">in</span> conv_curves.items():</span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span>name<span class="sc">:22s}</span><span class="ss"> </span><span class="sc">{</span>curve[<span class="dv">14</span>]<span class="sc">:10.4f}</span><span class="ss"> </span><span class="sc">{</span>curve[<span class="dv">49</span>]<span class="sc">:10.4f}</span><span class="ss"> </span><span class="sc">{</span>curve[<span class="op">-</span><span class="dv">1</span>]<span class="sc">:10.4f}</span><span class="ss"> </span><span class="sc">{</span>curve[<span class="op">-</span><span class="dv">1</span>]<span class="op">-</span>curve[<span class="dv">49</span>]<span class="sc">:+11.4f}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="CNC_Failure_Distribution_Shift_files/figure-html/cell-23-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Model                     best@15    best@50    best@60  gain 50→60
Logistic Regression        0.2685     0.2731     0.2731     +0.0000
Random Forest              0.6582     0.6596     0.6596     +0.0000
HistGradientBoosting       0.6584     0.6584     0.6584     +0.0000</code></pre>
</div>
</div>
<div id="f625a376" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T03:06:39.422663Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T03:06:39.422578Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T03:06:39.620592Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T03:06:39.619954Z&quot;}}" data-execution_count="23">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>palette<span class="op">=</span>{<span class="st">'Random Forest'</span>:C_B,<span class="st">'HistGradientBoosting'</span>:C_A,<span class="st">'Logistic Regression'</span>:C_GREY}</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="fl">13.5</span>, <span class="dv">4</span>))</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>ax<span class="op">=</span>axes[<span class="dv">0</span>]<span class="op">;</span> mc<span class="op">=</span>model_cmp.set_index(<span class="st">'Model'</span>)<span class="op">;</span> metrics<span class="op">=</span>[<span class="st">'AUC_ROC'</span>,<span class="st">'AUC_PR'</span>,<span class="st">'F1@thr*'</span>]</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>x<span class="op">=</span>np.arange(<span class="bu">len</span>(metrics))<span class="op">;</span> wbar<span class="op">=</span><span class="fl">0.25</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i,mname <span class="kw">in</span> <span class="bu">enumerate</span>(model_cmp[<span class="st">'Model'</span>]):</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>    ax.bar(x<span class="op">+</span>i<span class="op">*</span>wbar, mc.loc[mname,metrics].values, wbar, label<span class="op">=</span>mname, color<span class="op">=</span>palette[mname])</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>ax.set_xticks(x<span class="op">+</span>wbar)<span class="op">;</span> ax.set_xticklabels(metrics, fontsize<span class="op">=</span><span class="dv">8</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">'Điểm'</span>)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'So sánh mô hình trên Dây chuyền B'</span>)<span class="op">;</span> ax.set_ylim(<span class="dv">0</span>,<span class="dv">1</span>)<span class="op">;</span> ax.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>ax<span class="op">=</span>axes[<span class="dv">1</span>]</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> mname,p <span class="kw">in</span> proba_store.items():</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>    fpr,tpr,_<span class="op">=</span>roc_curve(yte,p)<span class="op">;</span> ax.plot(fpr,tpr,color<span class="op">=</span>palette[mname],lw<span class="op">=</span><span class="fl">1.6</span>,label<span class="op">=</span><span class="ss">f'</span><span class="sc">{</span>mname<span class="sc">}</span><span class="ss"> (</span><span class="sc">{</span>roc_auc_score(yte,p)<span class="sc">:.3f}</span><span class="ss">)'</span>)</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>ax.plot([<span class="dv">0</span>,<span class="dv">1</span>],[<span class="dv">0</span>,<span class="dv">1</span>],<span class="st">'k:'</span>,lw<span class="op">=</span><span class="fl">0.8</span>)<span class="op">;</span> ax.set_xlabel(<span class="st">'FPR'</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">'TPR'</span>)<span class="op">;</span> ax.set_title(<span class="st">'ROC curve'</span>)<span class="op">;</span> ax.legend(frameon<span class="op">=</span><span class="va">False</span>,fontsize<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>ax<span class="op">=</span>axes[<span class="dv">2</span>]</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> mname,p <span class="kw">in</span> proba_store.items():</span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>    pr,rc,_<span class="op">=</span>precision_recall_curve(yte,p)<span class="op">;</span> ax.plot(rc,pr,color<span class="op">=</span>palette[mname],lw<span class="op">=</span><span class="fl">1.6</span>,label<span class="op">=</span><span class="ss">f'</span><span class="sc">{</span>mname<span class="sc">}</span><span class="ss"> (</span><span class="sc">{</span>average_precision_score(yte,p)<span class="sc">:.3f}</span><span class="ss">)'</span>)</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>ax.axhline(yte.mean(),color<span class="op">=</span><span class="st">'k'</span>,ls<span class="op">=</span><span class="st">':'</span>,lw<span class="op">=</span><span class="fl">0.8</span>,label<span class="op">=</span><span class="ss">f'Ngẫu nhiên (</span><span class="sc">{</span>yte<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">)'</span>)</span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Recall'</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">'Precision'</span>)<span class="op">;</span> ax.set_title(<span class="st">'Precision-Recall curve'</span>)<span class="op">;</span> ax.legend(frameon<span class="op">=</span><span class="va">False</span>,fontsize<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">'Random Forest dẫn đầu trên dây chuyền chưa từng thấy (Dây chuyền B)'</span>, y<span class="op">=</span><span class="fl">1.03</span>)</span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="CNC_Failure_Distribution_Shift_files/figure-html/cell-24-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="chi-tiết-mô-hình-tốt-nhất-feature-importance-confusion-matrix" class="level3">
<h3 class="anchored" data-anchor-id="chi-tiết-mô-hình-tốt-nhất-feature-importance-confusion-matrix">4.3 Chi tiết mô hình tốt nhất: feature importance &amp; confusion matrix</h3>
<div id="ce0c5dca" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-07-18T03:06:39.622225Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-07-18T03:06:39.622102Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-07-18T03:06:39.830554Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-07-18T03:06:39.829861Z&quot;}}" data-execution_count="24">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>best_name <span class="op">=</span> model_cmp.iloc[<span class="dv">0</span>][<span class="st">'Model'</span>]<span class="op">;</span> best_model <span class="op">=</span> searches[best_name].best_estimator_</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>best_p <span class="op">=</span> proba_store[best_name]<span class="op">;</span> best_thr_v <span class="op">=</span> model_cmp.set_index(<span class="st">'Model'</span>).loc[best_name,<span class="st">'thr*'</span>]</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>best_pred <span class="op">=</span> (best_p<span class="op">&gt;=</span>best_thr_v).astype(<span class="bu">int</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">3.9</span>))</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>ax<span class="op">=</span>axes[<span class="dv">0</span>]</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="bu">hasattr</span>(best_model,<span class="st">'feature_importances_'</span>):</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>    fi <span class="op">=</span> pd.Series(best_model.feature_importances_, index<span class="op">=</span>FEATURES).sort_values()</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>    bars<span class="op">=</span>ax.barh(fi.index, fi.values, color<span class="op">=</span>[C_B <span class="cf">if</span> f <span class="kw">in</span> FE <span class="cf">else</span> C_A <span class="cf">for</span> f <span class="kw">in</span> fi.index])</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> b,v <span class="kw">in</span> <span class="bu">zip</span>(bars,fi.values): ax.text(v,b.get_y()<span class="op">+</span>b.get_height()<span class="op">/</span><span class="dv">2</span>,<span class="ss">f' </span><span class="sc">{</span>v<span class="sc">:.2f}</span><span class="ss">'</span>,va<span class="op">=</span><span class="st">'center'</span>,fontsize<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>    ax.legend(handles<span class="op">=</span>[Patch(color<span class="op">=</span>C_B,label<span class="op">=</span><span class="st">'Feature mới (cơ học)'</span>),Patch(color<span class="op">=</span>C_A,label<span class="op">=</span><span class="st">'Feature gốc'</span>)],</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>              frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">7</span>, loc<span class="op">=</span><span class="st">'lower right'</span>)</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Độ quan trọng'</span>)<span class="op">;</span> ax.set_title(<span class="ss">f'</span><span class="sc">{</span>best_name<span class="sc">}</span><span class="ss">: feature quan trọng'</span>)<span class="op">;</span> ax.margins(x<span class="op">=</span><span class="fl">0.12</span>)</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>ax<span class="op">=</span>axes[<span class="dv">1</span>]<span class="op">;</span> cm<span class="op">=</span>confusion_matrix(yte,best_pred)</span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>sns.heatmap(cm, annot<span class="op">=</span><span class="va">True</span>, fmt<span class="op">=</span><span class="st">',d'</span>, cmap<span class="op">=</span><span class="st">'Blues'</span>, cbar<span class="op">=</span><span class="va">False</span>, ax<span class="op">=</span>ax,</span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>            xticklabels<span class="op">=</span>[<span class="st">'Dự báo BT'</span>,<span class="st">'Dự báo HỎNG'</span>], yticklabels<span class="op">=</span>[<span class="st">'Thực BT'</span>,<span class="st">'Thực HỎNG'</span>], annot_kws<span class="op">=</span>{<span class="st">'fontsize'</span>:<span class="dv">11</span>})</span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>tn,fp,fn,tp<span class="op">=</span>cm.ravel()</span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="ss">f'Confusion Matrix (thr=</span><span class="sc">{</span>best_thr_v<span class="sc">:.2f}</span><span class="ss">)</span><span class="ch">\n</span><span class="ss">Bắt </span><span class="sc">{</span>tp<span class="sc">}</span><span class="ss">/</span><span class="sc">{</span>tp<span class="op">+</span>fn<span class="sc">}</span><span class="ss"> ca hỏng — recall </span><span class="sc">{</span>tp<span class="op">/</span>(tp<span class="op">+</span>fn)<span class="op">*</span><span class="dv">100</span><span class="sc">:.0f}</span><span class="ss">%, precision </span><span class="sc">{</span>tp<span class="op">/</span>(tp<span class="op">+</span>fp)<span class="op">*</span><span class="dv">100</span><span class="sc">:.0f}</span><span class="ss">%'</span>)</span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="ss">f'Mô hình tốt nhất: </span><span class="sc">{</span>best_name<span class="sc">}</span><span class="ss">'</span>, y<span class="op">=</span><span class="fl">1.04</span>)<span class="op">;</span> fig.tight_layout()<span class="op">;</span> plt.show()</span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span>best_name<span class="sc">}</span><span class="ss">: Recall=</span><span class="sc">{</span>tp<span class="op">/</span>(tp<span class="op">+</span>fn)<span class="sc">:.3f}</span><span class="ss">  Precision=</span><span class="sc">{</span>tp<span class="op">/</span>(tp<span class="op">+</span>fp)<span class="sc">:.3f}</span><span class="ss">  False alarm=</span><span class="sc">{</span>fp<span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="CNC_Failure_Distribution_Shift_files/figure-html/cell-25-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Random Forest: Recall=0.751  Precision=0.801  False alarm=89</code></pre>
</div>
</div>
<p><strong>Nhận xét Phần 4.</strong> - <strong>Random Forest thắng</strong>: AUC-ROC ≈ <strong>0.88</strong>, AUC-PR ≈ <strong>0.69</strong>, <strong>F1 = 0.775</strong> trên Dây chuyền B (tại thr* = 0.695, chọn trên OOF train — trung bình 5 seed) — vượt xa mức ngẫu nhiên (AUC-PR baseline = tỉ lệ dương ≈ 0.08). HistGBM sát nút (F1 0.769); <strong>Logistic Regression thua rõ</strong> (AUC-PR ≈ 0.24) vì quan hệ hỏng-hóc phi tuyến (chữ U của công suất, điểm gãy của độ mòn dao) — mô hình tuyến tính không nắm được. - <strong>F1 (con số so sánh giữa các nhóm) = 0.775</strong> tại thr* = 0.695 — ngưỡng chọn trên OOF train, trung bình 5 seed. - <strong>Confusion matrix:</strong> bắt <strong>358/477 ca hỏng (recall 75%)</strong> với chỉ <strong>89 báo động giả</strong> trên 6000 mẫu (precision 80%) → false alarm rất thấp, phù hợp bảo trì chủ động. - <strong>Feature importance:</strong> <code>do_mon_dao</code> mạnh nhất (0.30); hai vị trí tiếp theo là feature tự tạo <strong><code>cong_suat_co</code></strong> và <strong><code>chenh_lech_nhiet</code></strong> (0.16 mỗi biến); cả <strong>4 feature cơ học đều nằm trong top-7</strong>, còn biến phân loại ≈ 0 → khẳng định giá trị của Feature Engineering.</p>
<hr>
</section>
</section>
<section id="phần-5-báo-cáo-cuối-khoá" class="level1">
<h1>Phần 5 — Báo cáo cuối khoá</h1>
<section id="tóm-tắt-phương-pháp" class="level2">
<h2 class="anchored" data-anchor-id="tóm-tắt-phương-pháp">5.1 Tóm tắt phương pháp</h2>
<p>Pipeline 5 bước: <strong>EDA → Tiền xử lý &amp; Feature Engineering (chống rò rỉ) → Phát hiện &amp; Xử lý Distribution Shift → Mô hình (RandomizedSearch + Stratified K-Fold) → Đánh giá đa chiều.</strong> - Tạo <strong>4 feature cơ học</strong> ánh xạ trực tiếp cơ chế hỏng (tản nhiệt, công suất, quá tải, overstrain). - Scaler <strong>fit chỉ trên Train</strong>, transform cả hai tập → không rò rỉ Test. - Định lượng shift bằng <strong>PSI + KS-Test</strong>; xác nhận bằng <strong>Drift Classifier</strong> (AUC ≈ 0.83). - Xử lý shift bằng <strong>Threshold Calibration</strong> (và thử <strong>Importance Reweighting</strong>). - Huấn luyện &amp; so sánh <strong>3 mô hình</strong>, đánh giá trên Dây chuyền B chưa từng thấy.</p>
</section>
<section id="kết-quả-chính" class="level2">
<h2 class="anchored" data-anchor-id="kết-quả-chính">5.2 Kết quả chính</h2>
<ul>
<li><strong>Distribution shift là thật và mạnh:</strong> nhiệt độ môi trường có <strong>PSI ≈ 1.08</strong> (rất mạnh); drift classifier phân biệt hai dây chuyền với <strong>AUC ≈ 0.83</strong>. “Thủ phạm” chính là <strong>nhóm nhiệt độ</strong>.</li>
<li><strong>Mô hình tốt nhất — Random Forest:</strong> <strong>AUC-ROC ≈ 0.88, AUC-PR ≈ 0.69, F1 = 0.775</strong> trên Dây chuyền B; bắt <strong>358/477 ca hỏng (~75%)</strong> với chỉ <strong>89 báo động giả</strong> / 6000 mẫu.</li>
<li><strong>Feature Engineering có tác dụng đo được:</strong> +0.023 AUC-PR (CV); cả 4 feature tự tạo nằm trong <strong>top-7 độ quan trọng</strong> (vị trí #2–#3 là <code>cong_suat_co</code>, <code>chenh_lech_nhiet</code>); các feature cơ học này <strong>ổn định trước shift</strong> (PSI &lt; 0.05) — vừa dự báo tốt vừa tổng quát hoá tốt.</li>
<li><strong>Xử lý shift:</strong> <em>Threshold Calibration</em> nâng F1 <strong>0.757 → 0.771</strong>; <em>Importance Reweighting</em> không cải thiện (đúng lý thuyết covariate-shift thuần — P(y|x) ổn định).</li>
</ul>
</section>
<section id="insight-vận-hành-bảo-trì" class="level2">
<h2 class="anchored" data-anchor-id="insight-vận-hành-bảo-trì">5.3 Insight vận hành / bảo trì</h2>
<ol type="1">
<li><strong>Ưu tiên giám sát nhiệt độ &amp; tản nhiệt trên dây chuyền mới:</strong> shift lớn nhất đến từ nhiệt độ. Khi khánh thành dây chuyền ở khu vực nóng hơn, cần theo dõi <code>chenh_lech_nhiet</code> — chênh lệch nhiệt <strong>thấp</strong> (nhiệt quy trình gần sát nhiệt môi trường, máy không đẩy được nhiệt ra ngoài) mới là dấu hiệu tản nhiệt kém, <strong>không phải</strong> chênh lệch cao (kiểm chứng ở bảng ngũ phân vị mục 2.2: nhóm ΔT thấp nhất có tỉ lệ hỏng <strong>11.7%</strong> so với ~6% ở các nhóm còn lại). Môi trường nóng hơn còn làm ΔT <strong>co lại</strong> (trung bình ΔT ở B thấp hơn A ~0.6K) → dây chuyền đặt ở vùng khí hậu nóng càng cần cảnh báo sớm theo ΔT.</li>
<li><strong>Độ mòn dao là tín hiệu cảnh báo hàng đầu &amp; ổn định giữa các nhà máy:</strong> <code>do_mon_dao</code> quan trọng nhất và <em>không</em> bị shift → xây lịch <strong>thay dao chủ động theo ngưỡng mòn</strong> áp dụng được cho cả hai dây chuyền.</li>
<li><strong>Cảnh báo “quá tải căng thẳng”:</strong> <code>tich_mon_momen</code> / <code>strain_index</code> cao (dao mòn chịu mômen lớn ở tốc độ thấp) là tổ hợp nguy hiểm → đẩy cảnh báo cho tổ vận hành giảm tải hoặc thay dao ngay.</li>
<li><strong>Hiệu chỉnh ngưỡng theo chi phí:</strong> ngưỡng quyết định nên chọn theo cân bằng chi phí (bỏ sót 1 ca hỏng vs 1 lần dừng máy kiểm tra thừa), không cố định 0.5 — bỏ sót càng đắt thì ngưỡng càng nên hạ để tăng recall. Mô hình hiện bắt ~75% ca hỏng với false alarm rất thấp.</li>
</ol>
</section>
<section id="hạn-chế-hướng-cải-thiện" class="level2">
<h2 class="anchored" data-anchor-id="hạn-chế-hướng-cải-thiện">5.4 Hạn chế &amp; hướng cải thiện</h2>
<ul>
<li><strong>Chỉ có covariate shift được xử lý:</strong> nếu tương lai xuất hiện <strong>concept drift</strong> (cơ chế hỏng thay đổi, P(y|x) đổi), cần <strong>gán nhãn một phần dữ liệu Dây chuyền B</strong> và <em>fine-tune/online-learning</em>, vì reweighting sẽ không đủ.</li>
<li><strong>Không có chiều thời gian tường minh</strong> (ca kế tiếp) → chưa khai thác được đặc trưng chuỗi thời gian (xu hướng mòn dao, biên độ dao động nhiệt). Thu thập log theo thời gian sẽ mở ra feature mạnh hơn.</li>
<li><strong>Nhãn hiếm (~8%)</strong> → khoảng tin cậy của F1/AUC-PR còn rộng; nên <strong>lặp lại với nhiều seed</strong> và <strong>calibrate xác suất</strong> (Platt/Isotonic) trước khi ra quyết định theo chi phí.</li>
<li><strong>Domain adaptation nâng cao:</strong> có thể thử CORAL / adversarial feature alignment để căn chỉnh phân phối đặc trưng giữa hai dây chuyền — nằm ngoài phạm vi bài nhưng là hướng tự nhiên tiếp theo.</li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/quanglenhutthanh\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Built with Quarto · © 2026</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>